import { build } from 'esbuild';
import { mkdir, writeFile, copyFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
const root = fileURLToPath(new URL('../../', import.meta.url));
const out = root + 'CloudCode/nft/deploy/';
await mkdir(out, { recursive: true });
for (const name of ['Nft_GetChallenge', 'Nft_BindWallet', 'Nft_SyncInventory']) {
  const result = await build({ stdin: {
    contents: `import {verifyMessage,id} from 'ethers'; const {createNft}=require('../CloudCode/nft/core.cjs'); const {adapter}=require('../CloudCode/nft/adapter.cjs'); module.exports=async({params,context})=>createNft(adapter(context),context,{verifyMessage,id}).${name}(params||{});`,
    resolveDir: root + 'NFTWorkshop', sourcefile: name + '.js'
  }, bundle: true, platform: 'browser', format: 'cjs', target: 'es2020', minifyIdentifiers: true, minifySyntax: true, minifyWhitespace: false, write: false,
    external: ['@unity-services/*', 'axios-1.6'], legalComments: 'eof' });
  // Escape the Ethereum signed-message prefix's raw control character for Dashboard editors.
  const safeCode = result.outputFiles[0].text.replace(/[\x00-\x08\x0b\x0c\x0e-\x1f]/g,
    c => '\\u' + c.charCodeAt(0).toString(16).padStart(4, '0'));
  const text = '// NFT SYNC COPY V3 - ES2020, multiline, escaped control characters.\n// Generated by NFTWorkshop/scripts/build-sync.mjs. Edit CloudCode/nft sources.\n' + safeCode;
  if (Buffer.byteLength(text) >= 128000) throw Error('Cloud Code script exceeds size limit: ' + name);
  await writeFile(out + name + '.js', text);
  await writeFile(out + name + '_COPY.txt', text);
  console.log(name, Buffer.byteLength(text), 'bytes');
}
await copyFile(root + 'NFTWorkshop/node_modules/ethers/LICENSE.md', out + 'ETHERS_LICENSE.md');
await copyFile(root + 'NFTWorkshop/node_modules/@noble/curves/LICENSE', out + 'NOBLE_CURVES_LICENSE.txt');
await copyFile(root + 'NFTWorkshop/node_modules/@noble/hashes/LICENSE', out + 'NOBLE_HASHES_LICENSE.txt');
