// Dashboard scripts cannot require local files. Emit self-contained entry points.
const fs = require('node:fs');
const path = require('node:path');
const root = __dirname;
const core = fs.readFileSync(path.join(root, 'src/core.js'), 'utf8');
const adapter = ['cloud-store.js', 'cloud-adapter.js', 'cloud-market.js'].map(name => fs.readFileSync(path.join(root, 'src', name), 'utf8')).join('\n');
const endpoints = {
  Mkt_GetPlayer: [],
  Mkt_GrantDemo: [{ name: 'kind', type: 'String', required: true }],
  Sword_GetQuote: [],
  Sword_Claim: [{ name: 'tx_hash', type: 'String', required: true }],
  Gold_GetQuote: [],
  Gold_Claim: [{ name: 'tx_hash', type: 'String', required: true }],
  Mkt_GetActiveListings: [{ name: 'limit', type: 'Numeric', required: false }, { name: 'sort', type: 'String', required: false }],
  Mkt_CreateListing: [{ name: 'players_inventory_item_id', type: 'String', required: true }, { name: 'price', type: 'Numeric', required: true }, { name: 'currency_id', type: 'String', required: false }],
  Mkt_BuyListing: [{ name: 'listing_id', type: 'String', required: true }],
  Mkt_CancelListing: [{ name: 'listing_id', type: 'String', required: true }],
  Mkt_ClaimEarnings: [{ name: 'currency_id', type: 'String', required: false }],
  Mkt_Gacha: [{ name: 'request_id', type: 'String', required: true }]
};
for (const [name, params] of Object.entries(endpoints)) {
  if (name.startsWith('Mkt_') && !name.startsWith('Mkt_Get'))
    if (!params.some(p => p.name === 'request_id')) params.push({ name: 'request_id', type: 'String', required: true });
}
fs.mkdirSync(path.join(root, 'deploy'), { recursive: true });
for (const [name, params] of Object.entries(endpoints)) {
  const schema = Object.fromEntries(params.map(({ name, ...definition }) => [name, definition]));
  const body = `// ECONOMY-FREE V2. Generated by node build.js. Edit src/, then rebuild.\n${core}\n${adapter}\nmodule.exports = async (args) => createCloudMarket(createCloudAdapter(args.context), args.context).${name}(args.params || {});\nmodule.exports.params = ${JSON.stringify(schema, null, 2)};\n`;
  if (Buffer.byteLength(body) >= 128000) throw Error('SCRIPT_TOO_LARGE: ' + name);
  fs.writeFileSync(path.join(root, 'deploy', name + '.js'), body);
  if (name.startsWith('Mkt_')) fs.writeFileSync(path.join(root, '../js', name + '.txt'), body);
  if (name.startsWith('Sword_')) fs.writeFileSync(path.join(root, name + '_COPY_ALL.txt'), '// SWORD_SHOP_FULL_20260916_V5_RECOVERY\n' + body);
}
fs.writeFileSync(path.join(root, 'deploy', 'parameters.json'), JSON.stringify(endpoints, null, 2) + '\n');
console.log(`Built ${Object.keys(endpoints).length} Dashboard scripts.`);
