// NFT SYNC COPY V3 - ES2020, multiline, escaped control characters.
// Generated by NFTWorkshop/scripts/build-sync.mjs. Edit CloudCode/nft sources.
var Yr = Object.defineProperty;
var ze = (e) => {
  throw TypeError(e);
};
var je = (e, t) => () => (t || e((t = { exports: {} }).exports, t), t.exports), Fr = (e, t) => {
  for (var r in t)
    Yr(e, r, { get: t[r], enumerable: !0 });
};
var Ke = (e, t, r) => t.has(e) || ze("Cannot " + r);
var V = (e, t, r) => (Ke(e, t, "read from private field"), r ? r.call(e) : t.get(e)), bt = (e, t, r) => t.has(e) ? ze("Cannot add the same private member more than once") : t instanceof WeakSet ? t.add(e) : t.set(e, r), G = (e, t, r, n) => (Ke(e, t, "write to private field"), n ? n.call(e, r) : t.set(e, r), r);

// ../CloudCode/nft/core.cjs
var Zr = je((Ri, Kr) => {
  var De = "MYTHIC_SWORD_NFT";
  function Jn(e, t, r) {
    let n = t.playerId;
    if (!n || !t.projectId) throw Error("LOGIN_REQUIRED");
    let o = (c) => {
      if (!/^0x[0-9a-fA-F]{40}$/.test(c || "") || /^0x0{40}$/.test(c)) throw Error("INVALID_WALLET");
      return c.toLowerCase();
    };
    async function s() {
      let c = (await e.read("nft_config"))?.value;
      if (!c || !/^https:\/\//.test(c.rpcUrl || "")) throw Error("NFT_CONFIG_REQUIRED");
      return { ...c, contractAddress: o(c.contractAddress) };
    }
    async function i(c) {
      for (let a = 0; a < 5; a++) {
        let f = await e.read("nft_state");
        if (!f?.writeLock || f.value.version !== 1) throw Error("NFT_STATE_REQUIRED");
        let u = f.value;
        if (!u.bindings || !u.wallets || !u.challenges) throw Error("NFT_STATE_INVALID");
        for (let [g, I] of Object.entries(u.challenges)) I.expires < Date.now() && delete u.challenges[g];
        let l = c(u);
        if (JSON.stringify(u).length > 8e4) throw Error("NFT_STATE_CAPACITY");
        try {
          return await e.write("nft_state", u, f.writeLock), l;
        } catch (g) {
          if (Number(g.response?.status || g.status) !== 409) throw g;
        }
      }
      throw Error("NFT_BUSY_RETRY");
    }
    return {
      async Nft_GetChallenge(c) {
        let a = o(c.wallet_address), f = await s();
        return i((u) => {
          if (u.bindings[n]) {
            if (u.bindings[n] !== a) throw Error("PLAYER_ALREADY_LINKED");
            return { status: "LINKED", wallet: a };
          }
          if (u.wallets[a] && u.wallets[a] !== n) throw Error("WALLET_ALREADY_LINKED");
          u.sequence = (u.sequence || 0) + 1;
          let l = Date.now() + 3e5, g = [
            "Mythic Sword NFT - Link wallet",
            "No payment or token approval.",
            "Project: " + t.projectId,
            "Environment: " + t.environmentId,
            "Player: " + n,
            "Wallet: " + a,
            "Chain: 11155111",
            "Contract: " + f.contractAddress,
            "Nonce: " + u.sequence,
            "Expires: " + l
          ].join(`
`);
          return u.challenges[n] = { wallet: a, message: g, expires: l, contract: f.contractAddress }, { status: "SIGN_REQUIRED", wallet: a, message: g };
        });
      },
      async Nft_BindWallet(c) {
        let a = await s();
        return i((f) => {
          let u = f.challenges[n];
          if (!u || u.expires < Date.now() || u.contract !== a.contractAddress) throw Error("CHALLENGE_EXPIRED");
          let l;
          try {
            l = r.verifyMessage(u.message, c.signature).toLowerCase();
          } catch {
            throw Error("INVALID_SIGNATURE");
          }
          if (l !== u.wallet) throw Error("WRONG_SIGNER");
          if (f.bindings[n] && f.bindings[n] !== l) throw Error("PLAYER_ALREADY_LINKED");
          if (f.wallets[l] && f.wallets[l] !== n) throw Error("WALLET_ALREADY_LINKED");
          return f.bindings[n] = l, f.wallets[l] = n, delete f.challenges[n], { status: "LINKED", wallet: l };
        });
      },
      async Nft_SyncInventory() {
        let c = Date.now(), a = await s(), f = await i((u) => {
          if (!u.bindings[n]) return null;
          if (u.leases || (u.leases = {}), u.leases[n]?.until > Date.now()) throw Error("NFT_BUSY_RETRY");
          return u.sequence = (u.sequence || 0) + 1, u.leases[n] = { id: u.sequence, until: Date.now() + 6e4 }, { id: u.sequence, wallet: u.bindings[n] };
        });
        if (!f) return { status: "NOT_LINKED", count: 0 };
        try {
          await e.requireDefinition(n, De);
          let u = (x, U) => e.rpc(a.rpcUrl, x, U);
          if (BigInt(await u("eth_chainId", [])) !== 11155111n) throw Error("WRONG_CHAIN");
          let l = BigInt(await u("eth_blockNumber", []));
          if (l < 2n) throw Error("CHAIN_NOT_READY");
          let g = "0x" + (l - 2n).toString(16), I = await u("eth_getBlockByNumber", [g, !1]);
          if (!I?.hash) throw Error("INVALID_BLOCK");
          let b = async (x) => {
            let U = await u("eth_call", [{ to: a.contractAddress, data: x }, g]);
            if (!/^0x[0-9a-fA-F]{64}$/.test(U || "")) throw Error("INVALID_NFT_RESPONSE");
            return U;
          }, d = (x) => BigInt(x).toString(16).padStart(64, "0"), p = Number(BigInt(await b("0x70a08231" + f.wallet.slice(2).padStart(64, "0"))));
          if (!Number.isSafeInteger(p) || p > 20) throw Error("NFT_HOLDING_LIMIT_20");
          let y = await Promise.all(Array.from({ length: p }, async (x, U) => {
            let T = BigInt(await b("0x2f745c59" + f.wallet.slice(2).padStart(64, "0") + d(U))).toString();
            if ("0x" + (await b("0x6352211e" + d(T))).slice(-40).toLowerCase() !== f.wallet) throw Error("OWNER_MISMATCH");
            return T;
          }));
          if (new Set(y).size !== p) throw Error("DUPLICATE_CHAIN_TOKEN");
          let B = await e.inventory(n);
          if ((await u("eth_getBlockByNumber", [g, !1]))?.hash !== I.hash) throw Error("CHAIN_CHANGED_RETRY");
          let A = new Map(y.map((x) => [r.id("11155111:" + a.contractAddress + ":" + x).slice(2, 34), x])), k = /* @__PURE__ */ new Set(), v = [];
          for (let x of B.filter((U) => U.inventoryItemId === De)) {
            let U = A.get(x.playersInventoryItemId), T = x.instanceData || {};
            U && T.source === "MYTHIC_NFT" && T.contract === a.contractAddress && T.tokenId === U && T.wallet === f.wallet ? k.add(x.playersInventoryItemId) : v.push(x);
          }
          let w = 0, E = 0;
          for (let x of v) {
            if (Date.now() - c > 9500) return { status: "PARTIAL", count: p, added: w, removed: E };
            await e.removeItem(n, x), E++;
          }
          for (let [x, U] of A)
            if (!k.has(x)) {
              if (Date.now() - c > 9500) return { status: "PARTIAL", count: p, added: w, removed: E };
              await e.addItem(n, De, x, { source: "MYTHIC_NFT", chainId: 11155111, contract: a.contractAddress, tokenId: U, wallet: f.wallet }), w++;
            }
          return { status: "SYNCED", count: p, added: w, removed: E, wallet: f.wallet };
        } finally {
          await i((u) => {
            u.leases?.[n]?.id === f.id && delete u.leases[n];
          });
        }
      }
    };
  }
  Kr.exports = { createNft: Jn };
});

// ../CloudCode/nft/adapter.cjs
var Gr = je((Wr) => {
  var { DataApi: Qn } = require("@unity-services/cloud-save-1.4"), { ConfigurationApi: to, InventoryApi: eo } = require("@unity-services/economy-2.5"), ro = require("axios-1.6");
  Wr.adapter = (e) => {
    let t = { ...e, accessToken: e.serviceToken }, r = new Qn(t), n = new to(t), o = new eo(t), s = e.projectId, i, c = (a) => ({ projectId: s, playerId: a, configAssignmentHash: i });
    return {
      async read(a) {
        return (await r.getCustomItems(s, "simple_market", [a])).data.results.find((u) => u.key === a);
      },
      async write(a, f, u) {
        await r.setCustomItem(s, "simple_market", { key: a, value: f, writeLock: u });
      },
      async requireDefinition(a, f) {
        let u = await n.getPlayerConfiguration({ projectId: s, playerId: a });
        if (i = u.data.metadata.configAssignmentHash, !u.data.results.some((l) => l.id === f && l.type === "INVENTORY_ITEM")) throw Error("PUBLISH_MYTHIC_SWORD_NFT");
      },
      async rpc(a, f, u) {
        try {
          let l = await ro.post(a, { jsonrpc: "2.0", id: 1, method: f, params: u }, { timeout: 2500 });
          if (l.data.error || !Object.prototype.hasOwnProperty.call(l.data, "result")) throw Error();
          return l.data.result;
        } catch {
          throw Error("NFT_RPC_FAILED_RETRY");
        }
      },
      async inventory(a) {
        let f = [], u;
        for (let l = 0; l < 10; l++) {
          let g = await o.getPlayerInventory({ ...c(a), limit: 100, ...u ? { after: u } : {} });
          if (!Array.isArray(g.data.results)) throw Error("INVENTORY_RESPONSE_INVALID");
          if (f.push(...g.data.results), !g.data.links?.next) return f;
          let I = g.data.results.at(-1)?.playersInventoryItemId;
          if (!I || I === u) throw Error("INVENTORY_SCAN_INCOMPLETE");
          u = I;
        }
        throw Error("INVENTORY_SCAN_INCOMPLETE");
      },
      async addItem(a, f, u, l) {
        await o.addInventoryItem({ ...c(a), addInventoryRequest: { inventoryItemId: f, playersInventoryItemId: u, instanceData: l } });
      },
      async removeItem(a, f) {
        await o.deleteInventoryItem({ ...c(a), playersInventoryItemId: f.playersInventoryItemId, inventoryDeleteRequest: { writeLock: f.writeLock } });
      }
    };
  };
});

// node_modules/ethers/lib.esm/_version.js
var Ze = "6.15.0";

// node_modules/ethers/lib.esm/utils/properties.js
function Xr(e, t, r) {
  let n = t.split("|").map((s) => s.trim());
  for (let s = 0; s < n.length; s++)
    switch (t) {
      case "any":
        return;
      case "bigint":
      case "boolean":
      case "number":
      case "string":
        if (typeof e === t)
          return;
    }
  let o = new Error(`invalid value for type ${t}`);
  throw o.code = "INVALID_ARGUMENT", o.argument = `value.${r}`, o.value = e, o;
}
function pe(e, t, r) {
  for (let n in t) {
    let o = t[n], s = r ? r[n] : null;
    s && Xr(o, s, n), Object.defineProperty(e, n, { enumerable: !0, value: o, writable: !1 });
  }
}

// node_modules/ethers/lib.esm/utils/errors.js
function Ot(e, t) {
  if (e == null)
    return "null";
  if (t == null && (t = /* @__PURE__ */ new Set()), typeof e == "object") {
    if (t.has(e))
      return "[Circular]";
    t.add(e);
  }
  if (Array.isArray(e))
    return "[ " + e.map((r) => Ot(r, t)).join(", ") + " ]";
  if (e instanceof Uint8Array) {
    let r = "0123456789abcdef", n = "0x";
    for (let o = 0; o < e.length; o++)
      n += r[e[o] >> 4], n += r[e[o] & 15];
    return n;
  }
  if (typeof e == "object" && typeof e.toJSON == "function")
    return Ot(e.toJSON(), t);
  switch (typeof e) {
    case "boolean":
    case "number":
    case "symbol":
      return e.toString();
    case "bigint":
      return BigInt(e).toString();
    case "string":
      return JSON.stringify(e);
    case "object": {
      let r = Object.keys(e);
      return r.sort(), "{ " + r.map((n) => `${Ot(n, t)}: ${Ot(e[n], t)}`).join(", ") + " }";
    }
  }
  return "[ COULD NOT SERIALIZE ]";
}
function We(e, t, r) {
  let n = e;
  {
    let s = [];
    if (r) {
      if ("message" in r || "code" in r || "name" in r)
        throw new Error(`value will overwrite populated values: ${Ot(r)}`);
      for (let i in r) {
        if (i === "shortMessage")
          continue;
        let c = r[i];
        s.push(i + "=" + Ot(c));
      }
    }
    s.push(`code=${t}`), s.push(`version=${Ze}`), s.length && (e += " (" + s.join(", ") + ")");
  }
  let o;
  switch (t) {
    case "INVALID_ARGUMENT":
      o = new TypeError(e);
      break;
    case "NUMERIC_FAULT":
    case "BUFFER_OVERRUN":
      o = new RangeError(e);
      break;
    default:
      o = new Error(e);
  }
  return pe(o, { code: t }), r && Object.assign(o, r), o.shortMessage == null && pe(o, { shortMessage: n }), o;
}
function tt(e, t, r, n) {
  if (!e)
    throw We(t, r, n);
}
function N(e, t, r, n) {
  tt(e, t, "INVALID_ARGUMENT", { argument: r, value: n });
}
var Jr = ["NFD", "NFC", "NFKD", "NFKC"].reduce((e, t) => {
  try {
    if ("test".normalize(t) !== "test")
      throw new Error("bad");
    if (t === "NFD" && "\xE9".normalize("NFD") !== "e\u0301")
      throw new Error("broken");
    e.push(t);
  } catch {
  }
  return e;
}, []);
function ge(e) {
  tt(Jr.indexOf(e) >= 0, "platform missing String.prototype.normalize", "UNSUPPORTED_OPERATION", {
    operation: "String.prototype.normalize",
    info: { form: e }
  });
}
function ye(e, t, r) {
  if (r == null && (r = ""), e !== t) {
    let n = r, o = "new";
    r && (n += ".", o += " " + r), tt(!1, `private constructor; use ${n}from* methods`, "UNSUPPORTED_OPERATION", {
      operation: o
    });
  }
}

// node_modules/ethers/lib.esm/utils/data.js
function Ye(e, t, r) {
  if (e instanceof Uint8Array)
    return r ? new Uint8Array(e) : e;
  if (typeof e == "string" && e.match(/^0x(?:[0-9a-f][0-9a-f])*$/i)) {
    let n = new Uint8Array((e.length - 2) / 2), o = 2;
    for (let s = 0; s < n.length; s++)
      n[s] = parseInt(e.substring(o, o + 2), 16), o += 2;
    return n;
  }
  N(!1, "invalid BytesLike value", t || "value", e);
}
function q(e, t) {
  return Ye(e, t, !1);
}
function Et(e, t) {
  return Ye(e, t, !0);
}
function $t(e, t) {
  return !(typeof e != "string" || !e.match(/^0x[0-9A-Fa-f]*$/) || typeof t == "number" && e.length !== 2 + 2 * t || t === !0 && e.length % 2 !== 0);
}
var Ge = "0123456789abcdef";
function R(e) {
  let t = q(e), r = "0x";
  for (let n = 0; n < t.length; n++) {
    let o = t[n];
    r += Ge[(o & 240) >> 4] + Ge[o & 15];
  }
  return r;
}
function ut(e) {
  return "0x" + e.map((t) => R(t).substring(2)).join("");
}
function lt(e) {
  return $t(e, !0) ? (e.length - 2) / 2 : q(e).length;
}
function Qr(e, t, r) {
  let n = q(e);
  tt(t >= n.length, "padding exceeds data length", "BUFFER_OVERRUN", {
    buffer: new Uint8Array(n),
    length: t,
    offset: t + 1
  });
  let o = new Uint8Array(t);
  return o.fill(0), r ? o.set(n, t - n.length) : o.set(n, 0), R(o);
}
function me(e, t) {
  return Qr(e, t, !0);
}

// node_modules/ethers/lib.esm/utils/maths.js
var Fe = BigInt(0), go = BigInt(1), Rt = 9007199254740991;
function Bt(e, t) {
  switch (typeof e) {
    case "bigint":
      return e;
    case "number":
      return N(Number.isInteger(e), "underflow", t || "value", e), N(e >= -Rt && e <= Rt, "overflow", t || "value", e), BigInt(e);
    case "string":
      try {
        if (e === "")
          throw new Error("empty string");
        return e[0] === "-" && e[1] !== "-" ? -BigInt(e.substring(1)) : BigInt(e);
      } catch (r) {
        N(!1, `invalid BigNumberish string: ${r.message}`, t || "value", e);
      }
  }
  N(!1, "invalid BigNumberish value", t || "value", e);
}
function xe(e, t) {
  let r = Bt(e, t);
  return tt(r >= Fe, "unsigned value cannot be negative", "NUMERIC_FAULT", {
    fault: "overflow",
    operation: "getUint",
    value: e
  }), r;
}
function It(e, t) {
  switch (typeof e) {
    case "bigint":
      return N(e >= -Rt && e <= Rt, "overflow", t || "value", e), Number(e);
    case "number":
      return N(Number.isInteger(e), "underflow", t || "value", e), N(e >= -Rt && e <= Rt, "overflow", t || "value", e), e;
    case "string":
      try {
        if (e === "")
          throw new Error("empty string");
        return It(BigInt(e), t);
      } catch (r) {
        N(!1, `invalid numeric string: ${r.message}`, t || "value", e);
      }
  }
  N(!1, "invalid numeric value", t || "value", e);
}
function Yt(e, t) {
  let n = xe(e, "value").toString(16);
  if (t == null)
    n.length % 2 && (n = "0" + n);
  else {
    let o = It(t, "width");
    for (tt(o * 2 >= n.length, `value exceeds width (${o} bytes)`, "NUMERIC_FAULT", {
      operation: "toBeHex",
      fault: "overflow",
      value: e
    }); n.length < o * 2; )
      n = "0" + n;
  }
  return "0x" + n;
}
function we(e) {
  let t = xe(e, "value");
  if (t === Fe)
    return new Uint8Array([]);
  let r = t.toString(16);
  r.length % 2 && (r = "0" + r);
  let n = new Uint8Array(r.length / 2);
  for (let o = 0; o < n.length; o++) {
    let s = o * 2;
    n[o] = parseInt(r.substring(s, s + 2), 16);
  }
  return n;
}

// node_modules/ethers/lib.esm/utils/utf8.js
function tn(e, t, r, n, o) {
  N(!1, `invalid codepoint at offset ${t}; ${e}`, "bytes", r);
}
function Xe(e, t, r, n, o) {
  if (e === "BAD_PREFIX" || e === "UNEXPECTED_CONTINUE") {
    let s = 0;
    for (let i = t + 1; i < r.length && r[i] >> 6 === 2; i++)
      s++;
    return s;
  }
  return e === "OVERRUN" ? r.length - t - 1 : 0;
}
function en(e, t, r, n, o) {
  return e === "OVERLONG" ? (N(typeof o == "number", "invalid bad code point for replacement", "badCodepoint", o), n.push(o), 0) : (n.push(65533), Xe(e, t, r, n, o));
}
var rn = Object.freeze({
  error: tn,
  ignore: Xe,
  replace: en
});
function At(e, t) {
  N(typeof e == "string", "invalid string value", "str", e), t != null && (ge(t), e = e.normalize(t));
  let r = [];
  for (let n = 0; n < e.length; n++) {
    let o = e.charCodeAt(n);
    if (o < 128)
      r.push(o);
    else if (o < 2048)
      r.push(o >> 6 | 192), r.push(o & 63 | 128);
    else if ((o & 64512) == 55296) {
      n++;
      let s = e.charCodeAt(n);
      N(n < e.length && (s & 64512) === 56320, "invalid surrogate pair", "str", e);
      let i = 65536 + ((o & 1023) << 10) + (s & 1023);
      r.push(i >> 18 | 240), r.push(i >> 12 & 63 | 128), r.push(i >> 6 & 63 | 128), r.push(i & 63 | 128);
    } else
      r.push(o >> 12 | 224), r.push(o >> 6 & 63 | 128), r.push(o & 63 | 128);
  }
  return new Uint8Array(r);
}

// node_modules/@noble/hashes/esm/_assert.js
function zt(e) {
  if (!Number.isSafeInteger(e) || e < 0)
    throw new Error(`Wrong positive integer: ${e}`);
}
function jt(e, ...t) {
  if (!(e instanceof Uint8Array))
    throw new Error("Expected Uint8Array");
  if (t.length > 0 && !t.includes(e.length))
    throw new Error(`Expected Uint8Array of length ${t}, not of length=${e.length}`);
}
function Je(e) {
  if (typeof e != "function" || typeof e.create != "function")
    throw new Error("Hash should be wrapped by utils.wrapConstructor");
  zt(e.outputLen), zt(e.blockLen);
}
function et(e, t = !0) {
  if (e.destroyed)
    throw new Error("Hash instance has been destroyed");
  if (t && e.finished)
    throw new Error("Hash#digest() has already been called");
}
function Ft(e, t) {
  jt(e);
  let r = t.outputLen;
  if (e.length < r)
    throw new Error(`digestInto() expects output buffer of length at least ${r}`);
}

// node_modules/@noble/hashes/esm/crypto.js
var Xt = typeof globalThis == "object" && "crypto" in globalThis ? globalThis.crypto : void 0;

// node_modules/@noble/hashes/esm/utils.js
var Qe = (e) => e instanceof Uint8Array;
var tr = (e) => new Uint32Array(e.buffer, e.byteOffset, Math.floor(e.byteLength / 4)), Jt = (e) => new DataView(e.buffer, e.byteOffset, e.byteLength), F = (e, t) => e << 32 - t | e >>> t, nn = new Uint8Array(new Uint32Array([287454020]).buffer)[0] === 68;
if (!nn)
  throw new Error("Non little-endian hardware is not supported");
function on(e) {
  if (typeof e != "string")
    throw new Error(`utf8ToBytes expected string, got ${typeof e}`);
  return new Uint8Array(new TextEncoder().encode(e));
}
function ht(e) {
  if (typeof e == "string" && (e = on(e)), !Qe(e))
    throw new Error(`expected Uint8Array, got ${typeof e}`);
  return e;
}
function er(...e) {
  let t = new Uint8Array(e.reduce((n, o) => n + o.length, 0)), r = 0;
  return e.forEach((n) => {
    if (!Qe(n))
      throw new Error("Uint8Array expected");
    t.set(n, r), r += n.length;
  }), t;
}
var dt = class {
  // Safe version that clones internal state
  clone() {
    return this._cloneInto();
  }
}, $o = {}.toString;
function Qt(e) {
  let t = (n) => e().update(ht(n)).digest(), r = e();
  return t.outputLen = r.outputLen, t.blockLen = r.blockLen, t.create = () => e(), t;
}
function rr(e) {
  let t = (n, o) => e(o).update(ht(n)).digest(), r = e({});
  return t.outputLen = r.outputLen, t.blockLen = r.blockLen, t.create = (n) => e(n), t;
}
function nr(e = 32) {
  if (Xt && typeof Xt.getRandomValues == "function")
    return Xt.getRandomValues(new Uint8Array(e));
  throw new Error("crypto.getRandomValues must be defined");
}

// node_modules/@noble/hashes/esm/hmac.js
var te = class extends dt {
  constructor(t, r) {
    super(), this.finished = !1, this.destroyed = !1, Je(t);
    let n = ht(r);
    if (this.iHash = t.create(), typeof this.iHash.update != "function")
      throw new Error("Expected instance of class which extends utils.Hash");
    this.blockLen = this.iHash.blockLen, this.outputLen = this.iHash.outputLen;
    let o = this.blockLen, s = new Uint8Array(o);
    s.set(n.length > o ? t.create().update(n).digest() : n);
    for (let i = 0; i < s.length; i++)
      s[i] ^= 54;
    this.iHash.update(s), this.oHash = t.create();
    for (let i = 0; i < s.length; i++)
      s[i] ^= 106;
    this.oHash.update(s), s.fill(0);
  }
  update(t) {
    return et(this), this.iHash.update(t), this;
  }
  digestInto(t) {
    et(this), jt(t, this.outputLen), this.finished = !0, this.iHash.digestInto(t), this.oHash.update(t), this.oHash.digestInto(t), this.destroy();
  }
  digest() {
    let t = new Uint8Array(this.oHash.outputLen);
    return this.digestInto(t), t;
  }
  _cloneInto(t) {
    t || (t = Object.create(Object.getPrototypeOf(this), {}));
    let { oHash: r, iHash: n, finished: o, destroyed: s, blockLen: i, outputLen: c } = this;
    return t = t, t.finished = o, t.destroyed = s, t.blockLen = i, t.outputLen = c, t.oHash = r._cloneInto(t.oHash), t.iHash = n._cloneInto(t.iHash), t;
  }
  destroy() {
    this.destroyed = !0, this.oHash.destroy(), this.iHash.destroy();
  }
}, be = (e, t, r) => new te(e, t).update(r).digest();
be.create = (e, t) => new te(e, t);

// node_modules/@noble/hashes/esm/_sha2.js
function sn(e, t, r, n) {
  if (typeof e.setBigUint64 == "function")
    return e.setBigUint64(t, r, n);
  let o = BigInt(32), s = BigInt(4294967295), i = Number(r >> o & s), c = Number(r & s), a = n ? 4 : 0, f = n ? 0 : 4;
  e.setUint32(t + a, i, n), e.setUint32(t + f, c, n);
}
var ee = class extends dt {
  constructor(t, r, n, o) {
    super(), this.blockLen = t, this.outputLen = r, this.padOffset = n, this.isLE = o, this.finished = !1, this.length = 0, this.pos = 0, this.destroyed = !1, this.buffer = new Uint8Array(t), this.view = Jt(this.buffer);
  }
  update(t) {
    et(this);
    let { view: r, buffer: n, blockLen: o } = this;
    t = ht(t);
    let s = t.length;
    for (let i = 0; i < s; ) {
      let c = Math.min(o - this.pos, s - i);
      if (c === o) {
        let a = Jt(t);
        for (; o <= s - i; i += o)
          this.process(a, i);
        continue;
      }
      n.set(t.subarray(i, i + c), this.pos), this.pos += c, i += c, this.pos === o && (this.process(r, 0), this.pos = 0);
    }
    return this.length += t.length, this.roundClean(), this;
  }
  digestInto(t) {
    et(this), Ft(t, this), this.finished = !0;
    let { buffer: r, view: n, blockLen: o, isLE: s } = this, { pos: i } = this;
    r[i++] = 128, this.buffer.subarray(i).fill(0), this.padOffset > o - i && (this.process(n, 0), i = 0);
    for (let l = i; l < o; l++)
      r[l] = 0;
    sn(n, o - 8, BigInt(this.length * 8), s), this.process(n, 0);
    let c = Jt(t), a = this.outputLen;
    if (a % 4)
      throw new Error("_sha2: outputLen should be aligned to 32bit");
    let f = a / 4, u = this.get();
    if (f > u.length)
      throw new Error("_sha2: outputLen bigger than state");
    for (let l = 0; l < f; l++)
      c.setUint32(4 * l, u[l], s);
  }
  digest() {
    let { buffer: t, outputLen: r } = this;
    this.digestInto(t);
    let n = t.slice(0, r);
    return this.destroy(), n;
  }
  _cloneInto(t) {
    t || (t = new this.constructor()), t.set(...this.get());
    let { blockLen: r, buffer: n, length: o, finished: s, destroyed: i, pos: c } = this;
    return t.length = o, t.pos = c, t.finished = s, t.destroyed = i, o % r && t.buffer.set(n), t;
  }
};

// node_modules/@noble/hashes/esm/sha256.js
var cn = (e, t, r) => e & t ^ ~e & r, an = (e, t, r) => e & t ^ e & r ^ t & r, fn = /* @__PURE__ */ new Uint32Array([
  1116352408,
  1899447441,
  3049323471,
  3921009573,
  961987163,
  1508970993,
  2453635748,
  2870763221,
  3624381080,
  310598401,
  607225278,
  1426881987,
  1925078388,
  2162078206,
  2614888103,
  3248222580,
  3835390401,
  4022224774,
  264347078,
  604807628,
  770255983,
  1249150122,
  1555081692,
  1996064986,
  2554220882,
  2821834349,
  2952996808,
  3210313671,
  3336571891,
  3584528711,
  113926993,
  338241895,
  666307205,
  773529912,
  1294757372,
  1396182291,
  1695183700,
  1986661051,
  2177026350,
  2456956037,
  2730485921,
  2820302411,
  3259730800,
  3345764771,
  3516065817,
  3600352804,
  4094571909,
  275423344,
  430227734,
  506948616,
  659060556,
  883997877,
  958139571,
  1322822218,
  1537002063,
  1747873779,
  1955562222,
  2024104815,
  2227730452,
  2361852424,
  2428436474,
  2756734187,
  3204031479,
  3329325298
]), pt = /* @__PURE__ */ new Uint32Array([
  1779033703,
  3144134277,
  1013904242,
  2773480762,
  1359893119,
  2600822924,
  528734635,
  1541459225
]), gt = /* @__PURE__ */ new Uint32Array(64), Ee = class extends ee {
  constructor() {
    super(64, 32, 8, !1), this.A = pt[0] | 0, this.B = pt[1] | 0, this.C = pt[2] | 0, this.D = pt[3] | 0, this.E = pt[4] | 0, this.F = pt[5] | 0, this.G = pt[6] | 0, this.H = pt[7] | 0;
  }
  get() {
    let { A: t, B: r, C: n, D: o, E: s, F: i, G: c, H: a } = this;
    return [t, r, n, o, s, i, c, a];
  }
  // prettier-ignore
  set(t, r, n, o, s, i, c, a) {
    this.A = t | 0, this.B = r | 0, this.C = n | 0, this.D = o | 0, this.E = s | 0, this.F = i | 0, this.G = c | 0, this.H = a | 0;
  }
  process(t, r) {
    for (let l = 0; l < 16; l++, r += 4)
      gt[l] = t.getUint32(r, !1);
    for (let l = 16; l < 64; l++) {
      let g = gt[l - 15], I = gt[l - 2], b = F(g, 7) ^ F(g, 18) ^ g >>> 3, d = F(I, 17) ^ F(I, 19) ^ I >>> 10;
      gt[l] = d + gt[l - 7] + b + gt[l - 16] | 0;
    }
    let { A: n, B: o, C: s, D: i, E: c, F: a, G: f, H: u } = this;
    for (let l = 0; l < 64; l++) {
      let g = F(c, 6) ^ F(c, 11) ^ F(c, 25), I = u + g + cn(c, a, f) + fn[l] + gt[l] | 0, d = (F(n, 2) ^ F(n, 13) ^ F(n, 22)) + an(n, o, s) | 0;
      u = f, f = a, a = c, c = i + I | 0, i = s, s = o, o = n, n = I + d | 0;
    }
    n = n + this.A | 0, o = o + this.B | 0, s = s + this.C | 0, i = i + this.D | 0, c = c + this.E | 0, a = a + this.F | 0, f = f + this.G | 0, u = u + this.H | 0, this.set(n, o, s, i, c, a, f, u);
  }
  roundClean() {
    gt.fill(0);
  }
  destroy() {
    this.set(0, 0, 0, 0, 0, 0, 0, 0), this.buffer.fill(0);
  }
};
var or = /* @__PURE__ */ Qt(() => new Ee());

// node_modules/@noble/hashes/esm/_u64.js
var re = /* @__PURE__ */ BigInt(4294967295), sr = /* @__PURE__ */ BigInt(32);
function un(e, t = !1) {
  return t ? { h: Number(e & re), l: Number(e >> sr & re) } : { h: Number(e >> sr & re) | 0, l: Number(e & re) | 0 };
}
function ir(e, t = !1) {
  let r = new Uint32Array(e.length), n = new Uint32Array(e.length);
  for (let o = 0; o < e.length; o++) {
    let { h: s, l: i } = un(e[o], t);
    [r[o], n[o]] = [s, i];
  }
  return [r, n];
}
var cr = (e, t, r) => e << r | t >>> 32 - r, ar = (e, t, r) => t << r | e >>> 32 - r, fr = (e, t, r) => t << r - 32 | e >>> 64 - r, ur = (e, t, r) => e << r - 32 | t >>> 64 - r;

// node_modules/@noble/hashes/esm/sha3.js
var [hr, pr, gr] = [[], [], []], ln = /* @__PURE__ */ BigInt(0), Kt = /* @__PURE__ */ BigInt(1), dn = /* @__PURE__ */ BigInt(2), hn = /* @__PURE__ */ BigInt(7), pn = /* @__PURE__ */ BigInt(256), gn = /* @__PURE__ */ BigInt(113);
for (let e = 0, t = Kt, r = 1, n = 0; e < 24; e++) {
  [r, n] = [n, (2 * r + 3 * n) % 5], hr.push(2 * (5 * n + r)), pr.push((e + 1) * (e + 2) / 2 % 64);
  let o = ln;
  for (let s = 0; s < 7; s++)
    t = (t << Kt ^ (t >> hn) * gn) % pn, t & dn && (o ^= Kt << (Kt << /* @__PURE__ */ BigInt(s)) - Kt);
  gr.push(o);
}
var [yn, mn] = /* @__PURE__ */ ir(gr, !0), lr = (e, t, r) => r > 32 ? fr(e, t, r) : cr(e, t, r), dr = (e, t, r) => r > 32 ? ur(e, t, r) : ar(e, t, r);
function xn(e, t = 24) {
  let r = new Uint32Array(10);
  for (let n = 24 - t; n < 24; n++) {
    for (let i = 0; i < 10; i++)
      r[i] = e[i] ^ e[i + 10] ^ e[i + 20] ^ e[i + 30] ^ e[i + 40];
    for (let i = 0; i < 10; i += 2) {
      let c = (i + 8) % 10, a = (i + 2) % 10, f = r[a], u = r[a + 1], l = lr(f, u, 1) ^ r[c], g = dr(f, u, 1) ^ r[c + 1];
      for (let I = 0; I < 50; I += 10)
        e[i + I] ^= l, e[i + I + 1] ^= g;
    }
    let o = e[2], s = e[3];
    for (let i = 0; i < 24; i++) {
      let c = pr[i], a = lr(o, s, c), f = dr(o, s, c), u = hr[i];
      o = e[u], s = e[u + 1], e[u] = a, e[u + 1] = f;
    }
    for (let i = 0; i < 50; i += 10) {
      for (let c = 0; c < 10; c++)
        r[c] = e[i + c];
      for (let c = 0; c < 10; c++)
        e[i + c] ^= ~r[(c + 2) % 10] & r[(c + 4) % 10];
    }
    e[0] ^= yn[n], e[1] ^= mn[n];
  }
  r.fill(0);
}
var ne = class e extends dt {
  // NOTE: we accept arguments in bytes instead of bits here.
  constructor(t, r, n, o = !1, s = 24) {
    if (super(), this.blockLen = t, this.suffix = r, this.outputLen = n, this.enableXOF = o, this.rounds = s, this.pos = 0, this.posOut = 0, this.finished = !1, this.destroyed = !1, zt(n), 0 >= this.blockLen || this.blockLen >= 200)
      throw new Error("Sha3 supports only keccak-f1600 function");
    this.state = new Uint8Array(200), this.state32 = tr(this.state);
  }
  keccak() {
    xn(this.state32, this.rounds), this.posOut = 0, this.pos = 0;
  }
  update(t) {
    et(this);
    let { blockLen: r, state: n } = this;
    t = ht(t);
    let o = t.length;
    for (let s = 0; s < o; ) {
      let i = Math.min(r - this.pos, o - s);
      for (let c = 0; c < i; c++)
        n[this.pos++] ^= t[s++];
      this.pos === r && this.keccak();
    }
    return this;
  }
  finish() {
    if (this.finished)
      return;
    this.finished = !0;
    let { state: t, suffix: r, pos: n, blockLen: o } = this;
    t[n] ^= r, (r & 128) !== 0 && n === o - 1 && this.keccak(), t[o - 1] ^= 128, this.keccak();
  }
  writeInto(t) {
    et(this, !1), jt(t), this.finish();
    let r = this.state, { blockLen: n } = this;
    for (let o = 0, s = t.length; o < s; ) {
      this.posOut >= n && this.keccak();
      let i = Math.min(n - this.posOut, s - o);
      t.set(r.subarray(this.posOut, this.posOut + i), o), this.posOut += i, o += i;
    }
    return t;
  }
  xofInto(t) {
    if (!this.enableXOF)
      throw new Error("XOF is not possible for this instance");
    return this.writeInto(t);
  }
  xof(t) {
    return zt(t), this.xofInto(new Uint8Array(t));
  }
  digestInto(t) {
    if (Ft(t, this), this.finished)
      throw new Error("digest() was already called");
    return this.writeInto(t), this.destroy(), t;
  }
  digest() {
    return this.digestInto(new Uint8Array(this.outputLen));
  }
  destroy() {
    this.destroyed = !0, this.state.fill(0);
  }
  _cloneInto(t) {
    let { blockLen: r, suffix: n, outputLen: o, rounds: s, enableXOF: i } = this;
    return t || (t = new e(r, n, o, i, s)), t.state32.set(this.state32), t.pos = this.pos, t.posOut = this.posOut, t.finished = this.finished, t.rounds = s, t.suffix = n, t.outputLen = o, t.enableXOF = i, t.destroyed = this.destroyed, t;
  }
}, yt = (e, t, r) => Qt(() => new ne(t, e, r)), ns = /* @__PURE__ */ yt(6, 144, 224 / 8), os = /* @__PURE__ */ yt(6, 136, 256 / 8), ss = /* @__PURE__ */ yt(6, 104, 384 / 8), is = /* @__PURE__ */ yt(6, 72, 512 / 8), cs = /* @__PURE__ */ yt(1, 144, 224 / 8), yr = /* @__PURE__ */ yt(1, 136, 256 / 8), as = /* @__PURE__ */ yt(1, 104, 384 / 8), fs = /* @__PURE__ */ yt(1, 72, 512 / 8), mr = (e, t, r) => rr((n = {}) => new ne(t, e, n.dkLen === void 0 ? r : n.dkLen, !0)), us = /* @__PURE__ */ mr(31, 168, 128 / 8), ls = /* @__PURE__ */ mr(31, 136, 256 / 8);

// node_modules/ethers/lib.esm/crypto/keccak.js
var xr = !1, wr = function(e) {
  return yr(e);
}, br = wr;
function K(e) {
  let t = q(e, "data");
  return R(br(t));
}
K._ = wr;
K.lock = function() {
  xr = !0;
};
K.register = function(e) {
  if (xr)
    throw new TypeError("keccak256 is locked");
  br = e;
};
Object.freeze(K);

// node_modules/@noble/curves/esm/abstract/utils.js
var ve = {};
Fr(ve, {
  bitGet: () => vn,
  bitLen: () => An,
  bitMask: () => Zt,
  bitSet: () => Sn,
  bytesToHex: () => vt,
  bytesToNumberBE: () => rt,
  bytesToNumberLE: () => ie,
  concatBytes: () => Ct,
  createHmacDrbg: () => Ae,
  ensureBytes: () => Z,
  equalBytes: () => Bn,
  hexToBytes: () => St,
  hexToNumber: () => Ie,
  numberToBytesBE: () => mt,
  numberToBytesLE: () => ce,
  numberToHexUnpadded: () => Ir,
  numberToVarBytesBE: () => En,
  utf8ToBytes: () => In,
  validateObject: () => xt
});
var Br = BigInt(0), oe = BigInt(1), wn = BigInt(2), se = (e) => e instanceof Uint8Array, bn = /* @__PURE__ */ Array.from({ length: 256 }, (e, t) => t.toString(16).padStart(2, "0"));
function vt(e) {
  if (!se(e))
    throw new Error("Uint8Array expected");
  let t = "";
  for (let r = 0; r < e.length; r++)
    t += bn[e[r]];
  return t;
}
function Ir(e) {
  let t = e.toString(16);
  return t.length & 1 ? `0${t}` : t;
}
function Ie(e) {
  if (typeof e != "string")
    throw new Error("hex string expected, got " + typeof e);
  return BigInt(e === "" ? "0" : `0x${e}`);
}
function St(e) {
  if (typeof e != "string")
    throw new Error("hex string expected, got " + typeof e);
  let t = e.length;
  if (t % 2)
    throw new Error("padded hex string expected, got unpadded hex of length " + t);
  let r = new Uint8Array(t / 2);
  for (let n = 0; n < r.length; n++) {
    let o = n * 2, s = e.slice(o, o + 2), i = Number.parseInt(s, 16);
    if (Number.isNaN(i) || i < 0)
      throw new Error("Invalid byte sequence");
    r[n] = i;
  }
  return r;
}
function rt(e) {
  return Ie(vt(e));
}
function ie(e) {
  if (!se(e))
    throw new Error("Uint8Array expected");
  return Ie(vt(Uint8Array.from(e).reverse()));
}
function mt(e, t) {
  return St(e.toString(16).padStart(t * 2, "0"));
}
function ce(e, t) {
  return mt(e, t).reverse();
}
function En(e) {
  return St(Ir(e));
}
function Z(e, t, r) {
  let n;
  if (typeof t == "string")
    try {
      n = St(t);
    } catch (s) {
      throw new Error(`${e} must be valid hex string, got "${t}". Cause: ${s}`);
    }
  else if (se(t))
    n = Uint8Array.from(t);
  else
    throw new Error(`${e} must be hex string or Uint8Array`);
  let o = n.length;
  if (typeof r == "number" && o !== r)
    throw new Error(`${e} expected ${r} bytes, got ${o}`);
  return n;
}
function Ct(...e) {
  let t = new Uint8Array(e.reduce((n, o) => n + o.length, 0)), r = 0;
  return e.forEach((n) => {
    if (!se(n))
      throw new Error("Uint8Array expected");
    t.set(n, r), r += n.length;
  }), t;
}
function Bn(e, t) {
  if (e.length !== t.length)
    return !1;
  for (let r = 0; r < e.length; r++)
    if (e[r] !== t[r])
      return !1;
  return !0;
}
function In(e) {
  if (typeof e != "string")
    throw new Error(`utf8ToBytes expected string, got ${typeof e}`);
  return new Uint8Array(new TextEncoder().encode(e));
}
function An(e) {
  let t;
  for (t = 0; e > Br; e >>= oe, t += 1)
    ;
  return t;
}
function vn(e, t) {
  return e >> BigInt(t) & oe;
}
var Sn = (e, t, r) => e | (r ? oe : Br) << BigInt(t), Zt = (e) => (wn << BigInt(e - 1)) - oe, Be = (e) => new Uint8Array(e), Er = (e) => Uint8Array.from(e);
function Ae(e, t, r) {
  if (typeof e != "number" || e < 2)
    throw new Error("hashLen must be a number");
  if (typeof t != "number" || t < 2)
    throw new Error("qByteLen must be a number");
  if (typeof r != "function")
    throw new Error("hmacFn must be a function");
  let n = Be(e), o = Be(e), s = 0, i = () => {
    n.fill(1), o.fill(0), s = 0;
  }, c = (...l) => r(o, n, ...l), a = (l = Be()) => {
    o = c(Er([0]), l), n = c(), l.length !== 0 && (o = c(Er([1]), l), n = c());
  }, f = () => {
    if (s++ >= 1e3)
      throw new Error("drbg: tried 1000 values");
    let l = 0, g = [];
    for (; l < t; ) {
      n = c();
      let I = n.slice();
      g.push(I), l += n.length;
    }
    return Ct(...g);
  };
  return (l, g) => {
    i(), a(l);
    let I;
    for (; !(I = g(f())); )
      a();
    return i(), I;
  };
}
var Nn = {
  bigint: (e) => typeof e == "bigint",
  function: (e) => typeof e == "function",
  boolean: (e) => typeof e == "boolean",
  string: (e) => typeof e == "string",
  stringOrUint8Array: (e) => typeof e == "string" || e instanceof Uint8Array,
  isSafeInteger: (e) => Number.isSafeInteger(e),
  array: (e) => Array.isArray(e),
  field: (e, t) => t.Fp.isValid(e),
  hash: (e) => typeof e == "function" && Number.isSafeInteger(e.outputLen)
};
function xt(e, t, r = {}) {
  let n = (o, s, i) => {
    let c = Nn[s];
    if (typeof c != "function")
      throw new Error(`Invalid validator "${s}", expected function`);
    let a = e[o];
    if (!(i && a === void 0) && !c(a, e))
      throw new Error(`Invalid param ${String(o)}=${a} (${typeof a}), expected ${s}`);
  };
  for (let [o, s] of Object.entries(t))
    n(o, s, !1);
  for (let [o, s] of Object.entries(r))
    n(o, s, !0);
  return e;
}

// node_modules/@noble/curves/esm/abstract/modular.js
var C = BigInt(0), O = BigInt(1), Nt = BigInt(2), kn = BigInt(3), Se = BigInt(4), Ar = BigInt(5), vr = BigInt(8), Tn = BigInt(9), _n = BigInt(16);
function D(e, t) {
  let r = e % t;
  return r >= C ? r : t + r;
}
function Ln(e, t, r) {
  if (r <= C || t < C)
    throw new Error("Expected power/modulo > 0");
  if (r === O)
    return C;
  let n = O;
  for (; t > C; )
    t & O && (n = n * e % r), e = e * e % r, t >>= O;
  return n;
}
function W(e, t, r) {
  let n = e;
  for (; t-- > C; )
    n *= n, n %= r;
  return n;
}
function ae(e, t) {
  if (e === C || t <= C)
    throw new Error(`invert: expected positive integers, got n=${e} mod=${t}`);
  let r = D(e, t), n = t, o = C, s = O, i = O, c = C;
  for (; r !== C; ) {
    let f = n / r, u = n % r, l = o - i * f, g = s - c * f;
    n = r, r = u, o = i, s = c, i = l, c = g;
  }
  if (n !== O)
    throw new Error("invert: does not exist");
  return D(o, t);
}
function Un(e) {
  let t = (e - O) / Nt, r, n, o;
  for (r = e - O, n = 0; r % Nt === C; r /= Nt, n++)
    ;
  for (o = Nt; o < e && Ln(o, t, e) !== e - O; o++)
    ;
  if (n === 1) {
    let i = (e + O) / Se;
    return function(a, f) {
      let u = a.pow(f, i);
      if (!a.eql(a.sqr(u), f))
        throw new Error("Cannot find square root");
      return u;
    };
  }
  let s = (r + O) / Nt;
  return function(c, a) {
    if (c.pow(a, t) === c.neg(c.ONE))
      throw new Error("Cannot find square root");
    let f = n, u = c.pow(c.mul(c.ONE, o), r), l = c.pow(a, s), g = c.pow(a, r);
    for (; !c.eql(g, c.ONE); ) {
      if (c.eql(g, c.ZERO))
        return c.ZERO;
      let I = 1;
      for (let d = c.sqr(g); I < f && !c.eql(d, c.ONE); I++)
        d = c.sqr(d);
      let b = c.pow(u, O << BigInt(f - I - 1));
      u = c.sqr(b), l = c.mul(l, b), g = c.mul(g, u), f = I;
    }
    return l;
  };
}
function Pn(e) {
  if (e % Se === kn) {
    let t = (e + O) / Se;
    return function(n, o) {
      let s = n.pow(o, t);
      if (!n.eql(n.sqr(s), o))
        throw new Error("Cannot find square root");
      return s;
    };
  }
  if (e % vr === Ar) {
    let t = (e - Ar) / vr;
    return function(n, o) {
      let s = n.mul(o, Nt), i = n.pow(s, t), c = n.mul(o, i), a = n.mul(n.mul(c, Nt), i), f = n.mul(c, n.sub(a, n.ONE));
      if (!n.eql(n.sqr(f), o))
        throw new Error("Cannot find square root");
      return f;
    };
  }
  return e % _n, Un(e);
}
var On = [
  "create",
  "isValid",
  "is0",
  "neg",
  "inv",
  "sqrt",
  "sqr",
  "eql",
  "add",
  "sub",
  "mul",
  "pow",
  "div",
  "addN",
  "subN",
  "mulN",
  "sqrN"
];
function Ne(e) {
  let t = {
    ORDER: "bigint",
    MASK: "bigint",
    BYTES: "isSafeInteger",
    BITS: "isSafeInteger"
  }, r = On.reduce((n, o) => (n[o] = "function", n), t);
  return xt(e, r);
}
function Rn(e, t, r) {
  if (r < C)
    throw new Error("Expected power > 0");
  if (r === C)
    return e.ONE;
  if (r === O)
    return t;
  let n = e.ONE, o = t;
  for (; r > C; )
    r & O && (n = e.mul(n, o)), o = e.sqr(o), r >>= O;
  return n;
}
function Cn(e, t) {
  let r = new Array(t.length), n = t.reduce((s, i, c) => e.is0(i) ? s : (r[c] = s, e.mul(s, i)), e.ONE), o = e.inv(n);
  return t.reduceRight((s, i, c) => e.is0(i) ? s : (r[c] = e.mul(s, r[c]), e.mul(s, i)), o), r;
}
function ke(e, t) {
  let r = t !== void 0 ? t : e.toString(2).length, n = Math.ceil(r / 8);
  return { nBitLength: r, nByteLength: n };
}
function Sr(e, t, r = !1, n = {}) {
  if (e <= C)
    throw new Error(`Expected Field ORDER > 0, got ${e}`);
  let { nBitLength: o, nByteLength: s } = ke(e, t);
  if (s > 2048)
    throw new Error("Field lengths over 2048 bytes are not supported");
  let i = Pn(e), c = Object.freeze({
    ORDER: e,
    BITS: o,
    BYTES: s,
    MASK: Zt(o),
    ZERO: C,
    ONE: O,
    create: (a) => D(a, e),
    isValid: (a) => {
      if (typeof a != "bigint")
        throw new Error(`Invalid field element: expected bigint, got ${typeof a}`);
      return C <= a && a < e;
    },
    is0: (a) => a === C,
    isOdd: (a) => (a & O) === O,
    neg: (a) => D(-a, e),
    eql: (a, f) => a === f,
    sqr: (a) => D(a * a, e),
    add: (a, f) => D(a + f, e),
    sub: (a, f) => D(a - f, e),
    mul: (a, f) => D(a * f, e),
    pow: (a, f) => Rn(c, a, f),
    div: (a, f) => D(a * ae(f, e), e),
    // Same as above, but doesn't normalize
    sqrN: (a) => a * a,
    addN: (a, f) => a + f,
    subN: (a, f) => a - f,
    mulN: (a, f) => a * f,
    inv: (a) => ae(a, e),
    sqrt: n.sqrt || ((a) => i(c, a)),
    invertBatch: (a) => Cn(c, a),
    // TODO: do we really need constant cmov?
    // We don't have const-time bigints anyway, so probably will be not very useful
    cmov: (a, f, u) => u ? f : a,
    toBytes: (a) => r ? ce(a, s) : mt(a, s),
    fromBytes: (a) => {
      if (a.length !== s)
        throw new Error(`Fp.fromBytes: expected ${s}, got ${a.length}`);
      return r ? ie(a) : rt(a);
    }
  });
  return Object.freeze(c);
}
function Nr(e) {
  if (typeof e != "bigint")
    throw new Error("field order must be bigint");
  let t = e.toString(2).length;
  return Math.ceil(t / 8);
}
function Te(e) {
  let t = Nr(e);
  return t + Math.ceil(t / 2);
}
function kr(e, t, r = !1) {
  let n = e.length, o = Nr(t), s = Te(t);
  if (n < 16 || n < s || n > 1024)
    throw new Error(`expected ${s}-1024 bytes of input, got ${n}`);
  let i = r ? rt(e) : ie(e), c = D(i, t - O) + O;
  return r ? ce(c, o) : mt(c, o);
}

// node_modules/@noble/curves/esm/abstract/curve.js
var qn = BigInt(0), _e = BigInt(1);
function Tr(e, t) {
  let r = (o, s) => {
    let i = s.negate();
    return o ? i : s;
  }, n = (o) => {
    let s = Math.ceil(t / o) + 1, i = 2 ** (o - 1);
    return { windows: s, windowSize: i };
  };
  return {
    constTimeNegate: r,
    // non-const time multiplication ladder
    unsafeLadder(o, s) {
      let i = e.ZERO, c = o;
      for (; s > qn; )
        s & _e && (i = i.add(c)), c = c.double(), s >>= _e;
      return i;
    },
    /**
     * Creates a wNAF precomputation window. Used for caching.
     * Default window size is set by `utils.precompute()` and is equal to 8.
     * Number of precomputed points depends on the curve size:
     * 2^(𝑊−1) * (Math.ceil(𝑛 / 𝑊) + 1), where:
     * - 𝑊 is the window size
     * - 𝑛 is the bitlength of the curve order.
     * For a 256-bit curve and window size 8, the number of precomputed points is 128 * 33 = 4224.
     * @returns precomputed point tables flattened to a single array
     */
    precomputeWindow(o, s) {
      let { windows: i, windowSize: c } = n(s), a = [], f = o, u = f;
      for (let l = 0; l < i; l++) {
        u = f, a.push(u);
        for (let g = 1; g < c; g++)
          u = u.add(f), a.push(u);
        f = u.double();
      }
      return a;
    },
    /**
     * Implements ec multiplication using precomputed tables and w-ary non-adjacent form.
     * @param W window size
     * @param precomputes precomputed tables
     * @param n scalar (we don't check here, but should be less than curve order)
     * @returns real and fake (for const-time) points
     */
    wNAF(o, s, i) {
      let { windows: c, windowSize: a } = n(o), f = e.ZERO, u = e.BASE, l = BigInt(2 ** o - 1), g = 2 ** o, I = BigInt(o);
      for (let b = 0; b < c; b++) {
        let d = b * a, p = Number(i & l);
        i >>= I, p > a && (p -= g, i += _e);
        let y = d, B = d + Math.abs(p) - 1, A = b % 2 !== 0, k = p < 0;
        p === 0 ? u = u.add(r(A, s[y])) : f = f.add(r(k, s[B]));
      }
      return { p: f, f: u };
    },
    wNAFCached(o, s, i, c) {
      let a = o._WINDOW_SIZE || 1, f = s.get(o);
      return f || (f = this.precomputeWindow(o, a), a !== 1 && s.set(o, c(f))), this.wNAF(a, f, i);
    }
  };
}
function Le(e) {
  return Ne(e.Fp), xt(e, {
    n: "bigint",
    h: "bigint",
    Gx: "field",
    Gy: "field"
  }, {
    nBitLength: "isSafeInteger",
    nByteLength: "isSafeInteger"
  }), Object.freeze({
    ...ke(e.n, e.nBitLength),
    ...e,
    p: e.Fp.ORDER
  });
}

// node_modules/@noble/curves/esm/abstract/weierstrass.js
function Dn(e) {
  let t = Le(e);
  xt(t, {
    a: "field",
    b: "field"
  }, {
    allowedPrivateKeyLengths: "array",
    wrapPrivateKey: "boolean",
    isTorsionFree: "function",
    clearCofactor: "function",
    allowInfinityPoint: "boolean",
    fromBytes: "function",
    toBytes: "function"
  });
  let { endo: r, Fp: n, a: o } = t;
  if (r) {
    if (!n.eql(o, n.ZERO))
      throw new Error("Endomorphism can only be defined for Koblitz curves that have a=0");
    if (typeof r != "object" || typeof r.beta != "bigint" || typeof r.splitScalar != "function")
      throw new Error("Expected endomorphism with beta: bigint and splitScalar: function");
  }
  return Object.freeze({ ...t });
}
var { bytesToNumberBE: Vn, hexToBytes: Mn } = ve, kt = {
  // asn.1 DER encoding utils
  Err: class extends Error {
    constructor(t = "") {
      super(t);
    }
  },
  _parseInt(e) {
    let { Err: t } = kt;
    if (e.length < 2 || e[0] !== 2)
      throw new t("Invalid signature integer tag");
    let r = e[1], n = e.subarray(2, r + 2);
    if (!r || n.length !== r)
      throw new t("Invalid signature integer: wrong length");
    if (n[0] & 128)
      throw new t("Invalid signature integer: negative");
    if (n[0] === 0 && !(n[1] & 128))
      throw new t("Invalid signature integer: unnecessary leading zero");
    return { d: Vn(n), l: e.subarray(r + 2) };
  },
  toSig(e) {
    let { Err: t } = kt, r = typeof e == "string" ? Mn(e) : e;
    if (!(r instanceof Uint8Array))
      throw new Error("ui8a expected");
    let n = r.length;
    if (n < 2 || r[0] != 48)
      throw new t("Invalid signature tag");
    if (r[1] !== n - 2)
      throw new t("Invalid signature: incorrect length");
    let { d: o, l: s } = kt._parseInt(r.subarray(2)), { d: i, l: c } = kt._parseInt(s);
    if (c.length)
      throw new t("Invalid signature: left bytes after parsing");
    return { r: o, s: i };
  },
  hexFromSig(e) {
    let t = (f) => Number.parseInt(f[0], 16) & 8 ? "00" + f : f, r = (f) => {
      let u = f.toString(16);
      return u.length & 1 ? `0${u}` : u;
    }, n = t(r(e.s)), o = t(r(e.r)), s = n.length / 2, i = o.length / 2, c = r(s), a = r(i);
    return `30${r(i + s + 4)}02${a}${o}02${c}${n}`;
  }
}, nt = BigInt(0), Y = BigInt(1), Is = BigInt(2), _r = BigInt(3), As = BigInt(4);
function $n(e) {
  let t = Dn(e), { Fp: r } = t, n = t.toBytes || ((b, d, p) => {
    let y = d.toAffine();
    return Ct(Uint8Array.from([4]), r.toBytes(y.x), r.toBytes(y.y));
  }), o = t.fromBytes || ((b) => {
    let d = b.subarray(1), p = r.fromBytes(d.subarray(0, r.BYTES)), y = r.fromBytes(d.subarray(r.BYTES, 2 * r.BYTES));
    return { x: p, y };
  });
  function s(b) {
    let { a: d, b: p } = t, y = r.sqr(b), B = r.mul(y, b);
    return r.add(r.add(B, r.mul(b, d)), p);
  }
  if (!r.eql(r.sqr(t.Gy), s(t.Gx)))
    throw new Error("bad generator point: equation left != right");
  function i(b) {
    return typeof b == "bigint" && nt < b && b < t.n;
  }
  function c(b) {
    if (!i(b))
      throw new Error("Expected valid bigint: 0 < bigint < curve.n");
  }
  function a(b) {
    let { allowedPrivateKeyLengths: d, nByteLength: p, wrapPrivateKey: y, n: B } = t;
    if (d && typeof b != "bigint") {
      if (b instanceof Uint8Array && (b = vt(b)), typeof b != "string" || !d.includes(b.length))
        throw new Error("Invalid key");
      b = b.padStart(p * 2, "0");
    }
    let A;
    try {
      A = typeof b == "bigint" ? b : rt(Z("private key", b, p));
    } catch {
      throw new Error(`private key must be ${p} bytes, hex or bigint, not ${typeof b}`);
    }
    return y && (A = D(A, B)), c(A), A;
  }
  let f = /* @__PURE__ */ new Map();
  function u(b) {
    if (!(b instanceof l))
      throw new Error("ProjectivePoint expected");
  }
  class l {
    constructor(d, p, y) {
      if (this.px = d, this.py = p, this.pz = y, d == null || !r.isValid(d))
        throw new Error("x required");
      if (p == null || !r.isValid(p))
        throw new Error("y required");
      if (y == null || !r.isValid(y))
        throw new Error("z required");
    }
    // Does not validate if the point is on-curve.
    // Use fromHex instead, or call assertValidity() later.
    static fromAffine(d) {
      let { x: p, y } = d || {};
      if (!d || !r.isValid(p) || !r.isValid(y))
        throw new Error("invalid affine point");
      if (d instanceof l)
        throw new Error("projective point not allowed");
      let B = (A) => r.eql(A, r.ZERO);
      return B(p) && B(y) ? l.ZERO : new l(p, y, r.ONE);
    }
    get x() {
      return this.toAffine().x;
    }
    get y() {
      return this.toAffine().y;
    }
    /**
     * Takes a bunch of Projective Points but executes only one
     * inversion on all of them. Inversion is very slow operation,
     * so this improves performance massively.
     * Optimization: converts a list of projective points to a list of identical points with Z=1.
     */
    static normalizeZ(d) {
      let p = r.invertBatch(d.map((y) => y.pz));
      return d.map((y, B) => y.toAffine(p[B])).map(l.fromAffine);
    }
    /**
     * Converts hash string or Uint8Array to Point.
     * @param hex short/long ECDSA hex
     */
    static fromHex(d) {
      let p = l.fromAffine(o(Z("pointHex", d)));
      return p.assertValidity(), p;
    }
    // Multiplies generator point by privateKey.
    static fromPrivateKey(d) {
      return l.BASE.multiply(a(d));
    }
    // "Private method", don't use it directly
    _setWindowSize(d) {
      this._WINDOW_SIZE = d, f.delete(this);
    }
    // A point on curve is valid if it conforms to equation.
    assertValidity() {
      if (this.is0()) {
        if (t.allowInfinityPoint && !r.is0(this.py))
          return;
        throw new Error("bad point: ZERO");
      }
      let { x: d, y: p } = this.toAffine();
      if (!r.isValid(d) || !r.isValid(p))
        throw new Error("bad point: x or y not FE");
      let y = r.sqr(p), B = s(d);
      if (!r.eql(y, B))
        throw new Error("bad point: equation left != right");
      if (!this.isTorsionFree())
        throw new Error("bad point: not in prime-order subgroup");
    }
    hasEvenY() {
      let { y: d } = this.toAffine();
      if (r.isOdd)
        return !r.isOdd(d);
      throw new Error("Field doesn't support isOdd");
    }
    /**
     * Compare one point to another.
     */
    equals(d) {
      u(d);
      let { px: p, py: y, pz: B } = this, { px: A, py: k, pz: v } = d, w = r.eql(r.mul(p, v), r.mul(A, B)), E = r.eql(r.mul(y, v), r.mul(k, B));
      return w && E;
    }
    /**
     * Flips point to one corresponding to (x, -y) in Affine coordinates.
     */
    negate() {
      return new l(this.px, r.neg(this.py), this.pz);
    }
    // Renes-Costello-Batina exception-free doubling formula.
    // There is 30% faster Jacobian formula, but it is not complete.
    // https://eprint.iacr.org/2015/1060, algorithm 3
    // Cost: 8M + 3S + 3*a + 2*b3 + 15add.
    double() {
      let { a: d, b: p } = t, y = r.mul(p, _r), { px: B, py: A, pz: k } = this, v = r.ZERO, w = r.ZERO, E = r.ZERO, x = r.mul(B, B), U = r.mul(A, A), T = r.mul(k, k), _ = r.mul(B, A);
      return _ = r.add(_, _), E = r.mul(B, k), E = r.add(E, E), v = r.mul(d, E), w = r.mul(y, T), w = r.add(v, w), v = r.sub(U, w), w = r.add(U, w), w = r.mul(v, w), v = r.mul(_, v), E = r.mul(y, E), T = r.mul(d, T), _ = r.sub(x, T), _ = r.mul(d, _), _ = r.add(_, E), E = r.add(x, x), x = r.add(E, x), x = r.add(x, T), x = r.mul(x, _), w = r.add(w, x), T = r.mul(A, k), T = r.add(T, T), x = r.mul(T, _), v = r.sub(v, x), E = r.mul(T, U), E = r.add(E, E), E = r.add(E, E), new l(v, w, E);
    }
    // Renes-Costello-Batina exception-free addition formula.
    // There is 30% faster Jacobian formula, but it is not complete.
    // https://eprint.iacr.org/2015/1060, algorithm 1
    // Cost: 12M + 0S + 3*a + 3*b3 + 23add.
    add(d) {
      u(d);
      let { px: p, py: y, pz: B } = this, { px: A, py: k, pz: v } = d, w = r.ZERO, E = r.ZERO, x = r.ZERO, U = t.a, T = r.mul(t.b, _r), _ = r.mul(p, A), M = r.mul(y, k), $ = r.mul(B, v), it = r.add(p, y), h = r.add(A, k);
      it = r.mul(it, h), h = r.add(_, M), it = r.sub(it, h), h = r.add(p, B);
      let m = r.add(A, v);
      return h = r.mul(h, m), m = r.add(_, $), h = r.sub(h, m), m = r.add(y, B), w = r.add(k, v), m = r.mul(m, w), w = r.add(M, $), m = r.sub(m, w), x = r.mul(U, h), w = r.mul(T, $), x = r.add(w, x), w = r.sub(M, x), x = r.add(M, x), E = r.mul(w, x), M = r.add(_, _), M = r.add(M, _), $ = r.mul(U, $), h = r.mul(T, h), M = r.add(M, $), $ = r.sub(_, $), $ = r.mul(U, $), h = r.add(h, $), _ = r.mul(M, h), E = r.add(E, _), _ = r.mul(m, h), w = r.mul(it, w), w = r.sub(w, _), _ = r.mul(it, M), x = r.mul(m, x), x = r.add(x, _), new l(w, E, x);
    }
    subtract(d) {
      return this.add(d.negate());
    }
    is0() {
      return this.equals(l.ZERO);
    }
    wNAF(d) {
      return I.wNAFCached(this, f, d, (p) => {
        let y = r.invertBatch(p.map((B) => B.pz));
        return p.map((B, A) => B.toAffine(y[A])).map(l.fromAffine);
      });
    }
    /**
     * Non-constant-time multiplication. Uses double-and-add algorithm.
     * It's faster, but should only be used when you don't care about
     * an exposed private key e.g. sig verification, which works over *public* keys.
     */
    multiplyUnsafe(d) {
      let p = l.ZERO;
      if (d === nt)
        return p;
      if (c(d), d === Y)
        return this;
      let { endo: y } = t;
      if (!y)
        return I.unsafeLadder(this, d);
      let { k1neg: B, k1: A, k2neg: k, k2: v } = y.splitScalar(d), w = p, E = p, x = this;
      for (; A > nt || v > nt; )
        A & Y && (w = w.add(x)), v & Y && (E = E.add(x)), x = x.double(), A >>= Y, v >>= Y;
      return B && (w = w.negate()), k && (E = E.negate()), E = new l(r.mul(E.px, y.beta), E.py, E.pz), w.add(E);
    }
    /**
     * Constant time multiplication.
     * Uses wNAF method. Windowed method may be 10% faster,
     * but takes 2x longer to generate and consumes 2x memory.
     * Uses precomputes when available.
     * Uses endomorphism for Koblitz curves.
     * @param scalar by which the point would be multiplied
     * @returns New point
     */
    multiply(d) {
      c(d);
      let p = d, y, B, { endo: A } = t;
      if (A) {
        let { k1neg: k, k1: v, k2neg: w, k2: E } = A.splitScalar(p), { p: x, f: U } = this.wNAF(v), { p: T, f: _ } = this.wNAF(E);
        x = I.constTimeNegate(k, x), T = I.constTimeNegate(w, T), T = new l(r.mul(T.px, A.beta), T.py, T.pz), y = x.add(T), B = U.add(_);
      } else {
        let { p: k, f: v } = this.wNAF(p);
        y = k, B = v;
      }
      return l.normalizeZ([y, B])[0];
    }
    /**
     * Efficiently calculate `aP + bQ`. Unsafe, can expose private key, if used incorrectly.
     * Not using Strauss-Shamir trick: precomputation tables are faster.
     * The trick could be useful if both P and Q are not G (not in our case).
     * @returns non-zero affine point
     */
    multiplyAndAddUnsafe(d, p, y) {
      let B = l.BASE, A = (v, w) => w === nt || w === Y || !v.equals(B) ? v.multiplyUnsafe(w) : v.multiply(w), k = A(this, p).add(A(d, y));
      return k.is0() ? void 0 : k;
    }
    // Converts Projective point to affine (x, y) coordinates.
    // Can accept precomputed Z^-1 - for example, from invertBatch.
    // (x, y, z) ∋ (x=x/z, y=y/z)
    toAffine(d) {
      let { px: p, py: y, pz: B } = this, A = this.is0();
      d == null && (d = A ? r.ONE : r.inv(B));
      let k = r.mul(p, d), v = r.mul(y, d), w = r.mul(B, d);
      if (A)
        return { x: r.ZERO, y: r.ZERO };
      if (!r.eql(w, r.ONE))
        throw new Error("invZ was invalid");
      return { x: k, y: v };
    }
    isTorsionFree() {
      let { h: d, isTorsionFree: p } = t;
      if (d === Y)
        return !0;
      if (p)
        return p(l, this);
      throw new Error("isTorsionFree() has not been declared for the elliptic curve");
    }
    clearCofactor() {
      let { h: d, clearCofactor: p } = t;
      return d === Y ? this : p ? p(l, this) : this.multiplyUnsafe(t.h);
    }
    toRawBytes(d = !0) {
      return this.assertValidity(), n(l, this, d);
    }
    toHex(d = !0) {
      return vt(this.toRawBytes(d));
    }
  }
  l.BASE = new l(t.Gx, t.Gy, r.ONE), l.ZERO = new l(r.ZERO, r.ONE, r.ZERO);
  let g = t.nBitLength, I = Tr(l, t.endo ? Math.ceil(g / 2) : g);
  return {
    CURVE: t,
    ProjectivePoint: l,
    normPrivateKeyToScalar: a,
    weierstrassEquation: s,
    isWithinCurveOrder: i
  };
}
function zn(e) {
  let t = Le(e);
  return xt(t, {
    hash: "hash",
    hmac: "function",
    randomBytes: "function"
  }, {
    bits2int: "function",
    bits2int_modN: "function",
    lowS: "boolean"
  }), Object.freeze({ lowS: !0, ...t });
}
function Lr(e) {
  let t = zn(e), { Fp: r, n } = t, o = r.BYTES + 1, s = 2 * r.BYTES + 1;
  function i(h) {
    return nt < h && h < r.ORDER;
  }
  function c(h) {
    return D(h, n);
  }
  function a(h) {
    return ae(h, n);
  }
  let { ProjectivePoint: f, normPrivateKeyToScalar: u, weierstrassEquation: l, isWithinCurveOrder: g } = $n({
    ...t,
    toBytes(h, m, S) {
      let P = m.toAffine(), L = r.toBytes(P.x), H = Ct;
      return S ? H(Uint8Array.from([m.hasEvenY() ? 2 : 3]), L) : H(Uint8Array.from([4]), L, r.toBytes(P.y));
    },
    fromBytes(h) {
      let m = h.length, S = h[0], P = h.subarray(1);
      if (m === o && (S === 2 || S === 3)) {
        let L = rt(P);
        if (!i(L))
          throw new Error("Point is not on curve");
        let H = l(L), z = r.sqrt(H), j = (z & Y) === Y;
        return (S & 1) === 1 !== j && (z = r.neg(z)), { x: L, y: z };
      } else if (m === s && S === 4) {
        let L = r.fromBytes(P.subarray(0, r.BYTES)), H = r.fromBytes(P.subarray(r.BYTES, 2 * r.BYTES));
        return { x: L, y: H };
      } else
        throw new Error(`Point of length ${m} was invalid. Expected ${o} compressed bytes or ${s} uncompressed bytes`);
    }
  }), I = (h) => vt(mt(h, t.nByteLength));
  function b(h) {
    let m = n >> Y;
    return h > m;
  }
  function d(h) {
    return b(h) ? c(-h) : h;
  }
  let p = (h, m, S) => rt(h.slice(m, S));
  class y {
    constructor(m, S, P) {
      this.r = m, this.s = S, this.recovery = P, this.assertValidity();
    }
    // pair (bytes of r, bytes of s)
    static fromCompact(m) {
      let S = t.nByteLength;
      return m = Z("compactSignature", m, S * 2), new y(p(m, 0, S), p(m, S, 2 * S));
    }
    // DER encoded ECDSA signature
    // https://bitcoin.stackexchange.com/questions/57644/what-are-the-parts-of-a-bitcoin-transaction-input-script
    static fromDER(m) {
      let { r: S, s: P } = kt.toSig(Z("DER", m));
      return new y(S, P);
    }
    assertValidity() {
      if (!g(this.r))
        throw new Error("r must be 0 < r < CURVE.n");
      if (!g(this.s))
        throw new Error("s must be 0 < s < CURVE.n");
    }
    addRecoveryBit(m) {
      return new y(this.r, this.s, m);
    }
    recoverPublicKey(m) {
      let { r: S, s: P, recovery: L } = this, H = E(Z("msgHash", m));
      if (L == null || ![0, 1, 2, 3].includes(L))
        throw new Error("recovery id invalid");
      let z = L === 2 || L === 3 ? S + t.n : S;
      if (z >= r.ORDER)
        throw new Error("recovery id 2 or 3 invalid");
      let j = (L & 1) === 0 ? "02" : "03", ct = f.fromHex(j + I(z)), at = a(z), Lt = c(-H * at), Mt = c(P * at), ft = f.BASE.multiplyAndAddUnsafe(ct, Lt, Mt);
      if (!ft)
        throw new Error("point at infinify");
      return ft.assertValidity(), ft;
    }
    // Signatures should be low-s, to prevent malleability.
    hasHighS() {
      return b(this.s);
    }
    normalizeS() {
      return this.hasHighS() ? new y(this.r, c(-this.s), this.recovery) : this;
    }
    // DER-encoded
    toDERRawBytes() {
      return St(this.toDERHex());
    }
    toDERHex() {
      return kt.hexFromSig({ r: this.r, s: this.s });
    }
    // padded bytes of r, then padded bytes of s
    toCompactRawBytes() {
      return St(this.toCompactHex());
    }
    toCompactHex() {
      return I(this.r) + I(this.s);
    }
  }
  let B = {
    isValidPrivateKey(h) {
      try {
        return u(h), !0;
      } catch {
        return !1;
      }
    },
    normPrivateKeyToScalar: u,
    /**
     * Produces cryptographically secure private key from random of size
     * (groupLen + ceil(groupLen / 2)) with modulo bias being negligible.
     */
    randomPrivateKey: () => {
      let h = Te(t.n);
      return kr(t.randomBytes(h), t.n);
    },
    /**
     * Creates precompute table for an arbitrary EC point. Makes point "cached".
     * Allows to massively speed-up `point.multiply(scalar)`.
     * @returns cached point
     * @example
     * const fast = utils.precompute(8, ProjectivePoint.fromHex(someonesPubKey));
     * fast.multiply(privKey); // much faster ECDH now
     */
    precompute(h = 8, m = f.BASE) {
      return m._setWindowSize(h), m.multiply(BigInt(3)), m;
    }
  };
  function A(h, m = !0) {
    return f.fromPrivateKey(h).toRawBytes(m);
  }
  function k(h) {
    let m = h instanceof Uint8Array, S = typeof h == "string", P = (m || S) && h.length;
    return m ? P === o || P === s : S ? P === 2 * o || P === 2 * s : h instanceof f;
  }
  function v(h, m, S = !0) {
    if (k(h))
      throw new Error("first arg must be private key");
    if (!k(m))
      throw new Error("second arg must be public key");
    return f.fromHex(m).multiply(u(h)).toRawBytes(S);
  }
  let w = t.bits2int || function(h) {
    let m = rt(h), S = h.length * 8 - t.nBitLength;
    return S > 0 ? m >> BigInt(S) : m;
  }, E = t.bits2int_modN || function(h) {
    return c(w(h));
  }, x = Zt(t.nBitLength);
  function U(h) {
    if (typeof h != "bigint")
      throw new Error("bigint expected");
    if (!(nt <= h && h < x))
      throw new Error(`bigint expected < 2^${t.nBitLength}`);
    return mt(h, t.nByteLength);
  }
  function T(h, m, S = _) {
    if (["recovered", "canonical"].some((wt) => wt in S))
      throw new Error("sign() legacy options not supported");
    let { hash: P, randomBytes: L } = t, { lowS: H, prehash: z, extraEntropy: j } = S;
    H == null && (H = !0), h = Z("msgHash", h), z && (h = Z("prehashed msgHash", P(h)));
    let ct = E(h), at = u(m), Lt = [U(at), U(ct)];
    if (j != null) {
      let wt = j === !0 ? L(r.BYTES) : j;
      Lt.push(Z("extraEntropy", wt));
    }
    let Mt = Ct(...Lt), ft = ct;
    function he(wt) {
      let Ut = w(wt);
      if (!g(Ut))
        return;
      let Ve = a(Ut), J = f.BASE.multiply(Ut).toAffine(), Pt = c(J.x);
      if (Pt === nt)
        return;
      let Gt = c(Ve * c(ft + Pt * at));
      if (Gt === nt)
        return;
      let Me = (J.x === Pt ? 0 : 2) | Number(J.y & Y), $e = Gt;
      return H && b(Gt) && ($e = d(Gt), Me ^= 1), new y(Pt, $e, Me);
    }
    return { seed: Mt, k2sig: he };
  }
  let _ = { lowS: t.lowS, prehash: !1 }, M = { lowS: t.lowS, prehash: !1 };
  function $(h, m, S = _) {
    let { seed: P, k2sig: L } = T(h, m, S), H = t;
    return Ae(H.hash.outputLen, H.nByteLength, H.hmac)(P, L);
  }
  f.BASE._setWindowSize(8);
  function it(h, m, S, P = M) {
    let L = h;
    if (m = Z("msgHash", m), S = Z("publicKey", S), "strict" in P)
      throw new Error("options.strict was renamed to lowS");
    let { lowS: H, prehash: z } = P, j, ct;
    try {
      if (typeof L == "string" || L instanceof Uint8Array)
        try {
          j = y.fromDER(L);
        } catch (J) {
          if (!(J instanceof kt.Err))
            throw J;
          j = y.fromCompact(L);
        }
      else if (typeof L == "object" && typeof L.r == "bigint" && typeof L.s == "bigint") {
        let { r: J, s: Pt } = L;
        j = new y(J, Pt);
      } else
        throw new Error("PARSE");
      ct = f.fromHex(S);
    } catch (J) {
      if (J.message === "PARSE")
        throw new Error("signature must be Signature instance, Uint8Array or hex string");
      return !1;
    }
    if (H && j.hasHighS())
      return !1;
    z && (m = t.hash(m));
    let { r: at, s: Lt } = j, Mt = E(m), ft = a(Lt), he = c(Mt * ft), wt = c(at * ft), Ut = f.BASE.multiplyAndAddUnsafe(ct, he, wt)?.toAffine();
    return Ut ? c(Ut.x) === at : !1;
  }
  return {
    CURVE: t,
    getPublicKey: A,
    getSharedSecret: v,
    sign: $,
    verify: it,
    ProjectivePoint: f,
    Signature: y,
    utils: B
  };
}

// node_modules/@noble/curves/esm/_shortw_utils.js
function jn(e) {
  return {
    hash: e,
    hmac: (t, ...r) => be(e, t, er(...r)),
    randomBytes: nr
  };
}
function Ur(e, t) {
  let r = (n) => Lr({ ...e, ...jn(n) });
  return Object.freeze({ ...r(t), create: r });
}

// node_modules/@noble/curves/esm/secp256k1.js
var Rr = BigInt("0xfffffffffffffffffffffffffffffffffffffffffffffffffffffffefffffc2f"), Pr = BigInt("0xfffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141"), Kn = BigInt(1), Ue = BigInt(2), Or = (e, t) => (e + t / Ue) / t;
function Zn(e) {
  let t = Rr, r = BigInt(3), n = BigInt(6), o = BigInt(11), s = BigInt(22), i = BigInt(23), c = BigInt(44), a = BigInt(88), f = e * e * e % t, u = f * f * e % t, l = W(u, r, t) * u % t, g = W(l, r, t) * u % t, I = W(g, Ue, t) * f % t, b = W(I, o, t) * I % t, d = W(b, s, t) * b % t, p = W(d, c, t) * d % t, y = W(p, a, t) * p % t, B = W(y, c, t) * d % t, A = W(B, r, t) * u % t, k = W(A, i, t) * b % t, v = W(k, n, t) * f % t, w = W(v, Ue, t);
  if (!Pe.eql(Pe.sqr(w), e))
    throw new Error("Cannot find square root");
  return w;
}
var Pe = Sr(Rr, void 0, void 0, { sqrt: Zn }), ot = Ur({
  a: BigInt(0),
  b: BigInt(7),
  Fp: Pe,
  n: Pr,
  // Base point (x, y) aka generator point
  Gx: BigInt("55066263022277343669578718895168534326250603453777594175500187360389116729240"),
  Gy: BigInt("32670510020758816978083085130507043184471273380659243275938904335757337482424"),
  h: BigInt(1),
  lowS: !0,
  /**
   * secp256k1 belongs to Koblitz curves: it has efficiently computable endomorphism.
   * Endomorphism uses 2x less RAM, speeds up precomputation by 2x and ECDH / key recovery by 20%.
   * For precomputed wNAF it trades off 1/2 init time & 1/3 ram for 20% perf hit.
   * Explanation: https://gist.github.com/paulmillr/eb670806793e84df628a7c434a873066
   */
  endo: {
    beta: BigInt("0x7ae96a2b657c07106e64479eac3434e99cf0497512f58995c1396c28719501ee"),
    splitScalar: (e) => {
      let t = Pr, r = BigInt("0x3086d221a7d46bcde86c90e49284eb15"), n = -Kn * BigInt("0xe4437ed6010e88286f547fa90abfe4c3"), o = BigInt("0x114ca50f7a8e2f3f657c1108d9d44cfd8"), s = r, i = BigInt("0x100000000000000000000000000000000"), c = Or(s * e, t), a = Or(-n * e, t), f = D(e - c * r - a * o, t), u = D(-c * n - a * s, t), l = f > i, g = u > i;
      if (l && (f = t - f), g && (u = t - u), f > i || u > i)
        throw new Error("splitScalar: Endomorphism failed, k=" + e);
      return { k1neg: l, k1: f, k2neg: g, k2: u };
    }
  }
}, or), Ps = BigInt(0);
var Os = ot.ProjectivePoint;

// node_modules/ethers/lib.esm/constants/hashes.js
var fe = "0x0000000000000000000000000000000000000000000000000000000000000000";

// node_modules/ethers/lib.esm/constants/strings.js
var Oe = `\u0019Ethereum Signed Message:
`;

// node_modules/ethers/lib.esm/crypto/signature.js
var Cr = BigInt(0), Hr = BigInt(1), qr = BigInt(2), Dr = BigInt(27), Vr = BigInt(28), ue = BigInt(35), Ht = {};
function Mr(e) {
  return me(we(e), 32);
}
var qt, Q, Dt, Tt, X = class X {
  /**
   *  @private
   */
  constructor(t, r, n, o) {
    bt(this, qt);
    bt(this, Q);
    bt(this, Dt);
    bt(this, Tt);
    ye(t, Ht, "Signature"), G(this, qt, r), G(this, Q, n), G(this, Dt, o), G(this, Tt, null);
  }
  /**
   *  The ``r`` value for a signature.
   *
   *  This represents the ``x`` coordinate of a "reference" or
   *  challenge point, from which the ``y`` can be computed.
   */
  get r() {
    return V(this, qt);
  }
  set r(t) {
    N(lt(t) === 32, "invalid r", "value", t), G(this, qt, R(t));
  }
  /**
   *  The ``s`` value for a signature.
   */
  get s() {
    return N(parseInt(V(this, Q).substring(0, 3)) < 8, "non-canonical s; use ._s", "s", V(this, Q)), V(this, Q);
  }
  set s(t) {
    N(lt(t) === 32, "invalid s", "value", t), G(this, Q, R(t));
  }
  /**
   *  Return the s value, unchecked for EIP-2 compliance.
   *
   *  This should generally not be used and is for situations where
   *  a non-canonical S value might be relevant, such as Frontier blocks
   *  that were mined prior to EIP-2 or invalid Authorization List
   *  signatures.
   */
  get _s() {
    return V(this, Q);
  }
  /**
   *  Returns true if the Signature is valid for [[link-eip-2]] signatures.
   */
  isValid() {
    return parseInt(V(this, Q).substring(0, 3)) < 8;
  }
  /**
   *  The ``v`` value for a signature.
   *
   *  Since a given ``x`` value for ``r`` has two possible values for
   *  its correspondin ``y``, the ``v`` indicates which of the two ``y``
   *  values to use.
   *
   *  It is normalized to the values ``27`` or ``28`` for legacy
   *  purposes.
   */
  get v() {
    return V(this, Dt);
  }
  set v(t) {
    let r = It(t, "value");
    N(r === 27 || r === 28, "invalid v", "v", t), G(this, Dt, r);
  }
  /**
   *  The EIP-155 ``v`` for legacy transactions. For non-legacy
   *  transactions, this value is ``null``.
   */
  get networkV() {
    return V(this, Tt);
  }
  /**
   *  The chain ID for EIP-155 legacy transactions. For non-legacy
   *  transactions, this value is ``null``.
   */
  get legacyChainId() {
    let t = this.networkV;
    return t == null ? null : X.getChainId(t);
  }
  /**
   *  The ``yParity`` for the signature.
   *
   *  See ``v`` for more details on how this value is used.
   */
  get yParity() {
    return this.v === 27 ? 0 : 1;
  }
  /**
   *  The [[link-eip-2098]] compact representation of the ``yParity``
   *  and ``s`` compacted into a single ``bytes32``.
   */
  get yParityAndS() {
    let t = q(this.s);
    return this.yParity && (t[0] |= 128), R(t);
  }
  /**
   *  The [[link-eip-2098]] compact representation.
   */
  get compactSerialized() {
    return ut([this.r, this.yParityAndS]);
  }
  /**
   *  The serialized representation.
   */
  get serialized() {
    return ut([this.r, this.s, this.yParity ? "0x1c" : "0x1b"]);
  }
  [Symbol.for("nodejs.util.inspect.custom")]() {
    return `Signature { r: "${this.r}", s: "${this._s}"${this.isValid() ? "" : ', valid: "false"'}, yParity: ${this.yParity}, networkV: ${this.networkV} }`;
  }
  /**
   *  Returns a new identical [[Signature]].
   */
  clone() {
    let t = new X(Ht, this.r, this._s, this.v);
    return this.networkV && G(t, Tt, this.networkV), t;
  }
  /**
   *  Returns a representation that is compatible with ``JSON.stringify``.
   */
  toJSON() {
    let t = this.networkV;
    return {
      _type: "signature",
      networkV: t != null ? t.toString() : null,
      r: this.r,
      s: this._s,
      v: this.v
    };
  }
  /**
   *  Compute the chain ID from the ``v`` in a legacy EIP-155 transactions.
   *
   *  @example:
   *    Signature.getChainId(45)
   *    //_result:
   *
   *    Signature.getChainId(46)
   *    //_result:
   */
  static getChainId(t) {
    let r = Bt(t, "v");
    return r == Dr || r == Vr ? Cr : (N(r >= ue, "invalid EIP-155 v", "v", t), (r - ue) / qr);
  }
  /**
   *  Compute the ``v`` for a chain ID for a legacy EIP-155 transactions.
   *
   *  Legacy transactions which use [[link-eip-155]] hijack the ``v``
   *  property to include the chain ID.
   *
   *  @example:
   *    Signature.getChainIdV(5, 27)
   *    //_result:
   *
   *    Signature.getChainIdV(5, 28)
   *    //_result:
   *
   */
  static getChainIdV(t, r) {
    return Bt(t) * qr + BigInt(35 + r - 27);
  }
  /**
   *  Compute the normalized legacy transaction ``v`` from a ``yParirty``,
   *  a legacy transaction ``v`` or a legacy [[link-eip-155]] transaction.
   *
   *  @example:
   *    // The values 0 and 1 imply v is actually yParity
   *    Signature.getNormalizedV(0)
   *    //_result:
   *
   *    // Legacy non-EIP-1559 transaction (i.e. 27 or 28)
   *    Signature.getNormalizedV(27)
   *    //_result:
   *
   *    // Legacy EIP-155 transaction (i.e. >= 35)
   *    Signature.getNormalizedV(46)
   *    //_result:
   *
   *    // Invalid values throw
   *    Signature.getNormalizedV(5)
   *    //_error:
   */
  static getNormalizedV(t) {
    let r = Bt(t);
    return r === Cr || r === Dr ? 27 : r === Hr || r === Vr ? 28 : (N(r >= ue, "invalid v", "v", t), r & Hr ? 27 : 28);
  }
  /**
   *  Creates a new [[Signature]].
   *
   *  If no %%sig%% is provided, a new [[Signature]] is created
   *  with default values.
   *
   *  If %%sig%% is a string, it is parsed.
   */
  static from(t) {
    function r(f, u) {
      N(f, u, "signature", t);
    }
    if (t == null)
      return new X(Ht, fe, fe, 27);
    if (typeof t == "string") {
      let f = q(t, "signature");
      if (f.length === 64) {
        let u = R(f.slice(0, 32)), l = f.slice(32, 64), g = l[0] & 128 ? 28 : 27;
        return l[0] &= 127, new X(Ht, u, R(l), g);
      }
      if (f.length === 65) {
        let u = R(f.slice(0, 32)), l = R(f.slice(32, 64)), g = X.getNormalizedV(f[64]);
        return new X(Ht, u, l, g);
      }
      r(!1, "invalid raw signature length");
    }
    if (t instanceof X)
      return t.clone();
    let n = t.r;
    r(n != null, "missing r");
    let o = Mr(n), s = (function(f, u) {
      if (f != null)
        return Mr(f);
      if (u != null) {
        r($t(u, 32), "invalid yParityAndS");
        let l = q(u);
        return l[0] &= 127, R(l);
      }
      r(!1, "missing s");
    })(t.s, t.yParityAndS), { networkV: i, v: c } = (function(f, u, l) {
      if (f != null) {
        let g = Bt(f);
        return {
          networkV: g >= ue ? g : void 0,
          v: X.getNormalizedV(g)
        };
      }
      if (u != null)
        return r($t(u, 32), "invalid yParityAndS"), { v: q(u)[0] & 128 ? 28 : 27 };
      if (l != null) {
        switch (It(l, "sig.yParity")) {
          case 0:
            return { v: 27 };
          case 1:
            return { v: 28 };
        }
        r(!1, "invalid yParity");
      }
      r(!1, "missing v");
    })(t.v, t.yParityAndS, t.yParity), a = new X(Ht, o, s, c);
    return i && G(a, Tt, i), r(t.yParity == null || It(t.yParity, "sig.yParity") === a.yParity, "yParity mismatch"), r(t.yParityAndS == null || t.yParityAndS === a.yParityAndS, "yParityAndS mismatch"), a;
  }
};
qt = new WeakMap(), Q = new WeakMap(), Dt = new WeakMap(), Tt = new WeakMap();
var Wt = X;

// node_modules/ethers/lib.esm/crypto/signing-key.js
var st, _t = class _t {
  /**
   *  Creates a new **SigningKey** for %%privateKey%%.
   */
  constructor(t) {
    bt(this, st);
    N(lt(t) === 32, "invalid private key", "privateKey", "[REDACTED]"), G(this, st, R(t));
  }
  /**
   *  The private key.
   */
  get privateKey() {
    return V(this, st);
  }
  /**
   *  The uncompressed public key.
   *
   * This will always begin with the prefix ``0x04`` and be 132
   * characters long (the ``0x`` prefix and 130 hexadecimal nibbles).
   */
  get publicKey() {
    return _t.computePublicKey(V(this, st));
  }
  /**
   *  The compressed public key.
   *
   *  This will always begin with either the prefix ``0x02`` or ``0x03``
   *  and be 68 characters long (the ``0x`` prefix and 33 hexadecimal
   *  nibbles)
   */
  get compressedPublicKey() {
    return _t.computePublicKey(V(this, st), !0);
  }
  /**
   *  Return the signature of the signed %%digest%%.
   */
  sign(t) {
    N(lt(t) === 32, "invalid digest length", "digest", t);
    let r = ot.sign(Et(t), Et(V(this, st)), {
      lowS: !0
    });
    return Wt.from({
      r: Yt(r.r, 32),
      s: Yt(r.s, 32),
      v: r.recovery ? 28 : 27
    });
  }
  /**
   *  Returns the [[link-wiki-ecdh]] shared secret between this
   *  private key and the %%other%% key.
   *
   *  The %%other%% key may be any type of key, a raw public key,
   *  a compressed/uncompressed pubic key or aprivate key.
   *
   *  Best practice is usually to use a cryptographic hash on the
   *  returned value before using it as a symetric secret.
   *
   *  @example:
   *    sign1 = new SigningKey(id("some-secret-1"))
   *    sign2 = new SigningKey(id("some-secret-2"))
   *
   *    // Notice that privA.computeSharedSecret(pubB)...
   *    sign1.computeSharedSecret(sign2.publicKey)
   *    //_result:
   *
   *    // ...is equal to privB.computeSharedSecret(pubA).
   *    sign2.computeSharedSecret(sign1.publicKey)
   *    //_result:
   */
  computeSharedSecret(t) {
    let r = _t.computePublicKey(t);
    return R(ot.getSharedSecret(Et(V(this, st)), q(r), !1));
  }
  /**
   *  Compute the public key for %%key%%, optionally %%compressed%%.
   *
   *  The %%key%% may be any type of key, a raw public key, a
   *  compressed/uncompressed public key or private key.
   *
   *  @example:
   *    sign = new SigningKey(id("some-secret"));
   *
   *    // Compute the uncompressed public key for a private key
   *    SigningKey.computePublicKey(sign.privateKey)
   *    //_result:
   *
   *    // Compute the compressed public key for a private key
   *    SigningKey.computePublicKey(sign.privateKey, true)
   *    //_result:
   *
   *    // Compute the uncompressed public key
   *    SigningKey.computePublicKey(sign.publicKey, false);
   *    //_result:
   *
   *    // Compute the Compressed a public key
   *    SigningKey.computePublicKey(sign.publicKey, true);
   *    //_result:
   */
  static computePublicKey(t, r) {
    let n = q(t, "key");
    if (n.length === 32) {
      let s = ot.getPublicKey(n, !!r);
      return R(s);
    }
    if (n.length === 64) {
      let s = new Uint8Array(65);
      s[0] = 4, s.set(n, 1), n = s;
    }
    let o = ot.ProjectivePoint.fromHex(n);
    return R(o.toRawBytes(r));
  }
  /**
   *  Returns the public key for the private key which produced the
   *  %%signature%% for the given %%digest%%.
   *
   *  @example:
   *    key = new SigningKey(id("some-secret"))
   *    digest = id("hello world")
   *    sig = key.sign(digest)
   *
   *    // Notice the signer public key...
   *    key.publicKey
   *    //_result:
   *
   *    // ...is equal to the recovered public key
   *    SigningKey.recoverPublicKey(digest, sig)
   *    //_result:
   *
   */
  static recoverPublicKey(t, r) {
    N(lt(t) === 32, "invalid digest length", "digest", t);
    let n = Wt.from(r), o = ot.Signature.fromCompact(Et(ut([n.r, n.s])));
    o = o.addRecoveryBit(n.yParity);
    let s = o.recoverPublicKey(Et(t));
    return N(s != null, "invalid signature for digest", "signature", r), "0x" + s.toHex(!1);
  }
  /**
   *  Returns the point resulting from adding the ellipic curve points
   *  %%p0%% and %%p1%%.
   *
   *  This is not a common function most developers should require, but
   *  can be useful for certain privacy-specific techniques.
   *
   *  For example, it is used by [[HDNodeWallet]] to compute child
   *  addresses from parent public keys and chain codes.
   */
  static addPoints(t, r, n) {
    let o = ot.ProjectivePoint.fromHex(_t.computePublicKey(t).substring(2)), s = ot.ProjectivePoint.fromHex(_t.computePublicKey(r).substring(2));
    return "0x" + o.add(s).toHex(!!n);
  }
};
st = new WeakMap();
var Vt = _t;

// node_modules/ethers/lib.esm/address/address.js
var Wn = BigInt(0), Gn = BigInt(36);
function $r(e) {
  e = e.toLowerCase();
  let t = e.substring(2).split(""), r = new Uint8Array(40);
  for (let o = 0; o < 40; o++)
    r[o] = t[o].charCodeAt(0);
  let n = q(K(r));
  for (let o = 0; o < 40; o += 2)
    n[o >> 1] >> 4 >= 8 && (t[o] = t[o].toUpperCase()), (n[o >> 1] & 15) >= 8 && (t[o + 1] = t[o + 1].toUpperCase());
  return "0x" + t.join("");
}
var Re = {};
for (let e = 0; e < 10; e++)
  Re[String(e)] = String(e);
for (let e = 0; e < 26; e++)
  Re[String.fromCharCode(65 + e)] = String(10 + e);
var zr = 15;
function Yn(e) {
  e = e.toUpperCase(), e = e.substring(4) + e.substring(0, 2) + "00";
  let t = e.split("").map((n) => Re[n]).join("");
  for (; t.length >= zr; ) {
    let n = t.substring(0, zr);
    t = parseInt(n, 10) % 97 + t.substring(n.length);
  }
  let r = String(98 - parseInt(t, 10) % 97);
  for (; r.length < 2; )
    r = "0" + r;
  return r;
}
var Fn = (function() {
  let e = {};
  for (let t = 0; t < 36; t++) {
    let r = "0123456789abcdefghijklmnopqrstuvwxyz"[t];
    e[r] = BigInt(t);
  }
  return e;
})();
function Xn(e) {
  e = e.toLowerCase();
  let t = Wn;
  for (let r = 0; r < e.length; r++)
    t = t * Gn + Fn[e[r]];
  return t;
}
function Ce(e) {
  if (N(typeof e == "string", "invalid address", "address", e), e.match(/^(0x)?[0-9a-fA-F]{40}$/)) {
    e.startsWith("0x") || (e = "0x" + e);
    let t = $r(e);
    return N(!e.match(/([A-F].*[a-f])|([a-f].*[A-F])/) || t === e, "bad address checksum", "address", e), t;
  }
  if (e.match(/^XE[0-9]{2}[0-9A-Za-z]{30,31}$/)) {
    N(e.substring(2, 4) === Yn(e), "bad icap checksum", "address", e);
    let t = Xn(e.substring(4)).toString(16);
    for (; t.length < 40; )
      t = "0" + t;
    return $r("0x" + t);
  }
  N(!1, "invalid address", "address", e);
}

// node_modules/ethers/lib.esm/transaction/address.js
function jr(e) {
  let t;
  return typeof e == "string" ? t = Vt.computePublicKey(e, !1) : t = e.publicKey, Ce(K("0x" + t.substring(4)).substring(26));
}
function He(e, t) {
  return jr(Vt.recoverPublicKey(e, t));
}

// node_modules/ethers/lib.esm/hash/id.js
function le(e) {
  return K(At(e));
}

// node_modules/ethers/lib.esm/hash/message.js
function qe(e) {
  return typeof e == "string" && (e = At(e)), K(ut([
    At(Oe),
    At(String(e.length)),
    e
  ]));
}
function de(e, t) {
  let r = qe(e);
  return He(r, t);
}

// Nft_GetChallenge.js
var { createNft: no } = Zr(), { adapter: oo } = Gr();
module.exports = async ({ params: e, context: t }) => no(oo(t), t, { verifyMessage: de, id: le }).Nft_GetChallenge(e || {});
/*! Bundled license information:

@noble/hashes/esm/utils.js:
  (*! noble-hashes - MIT License (c) 2022 Paul Miller (paulmillr.com) *)

@noble/curves/esm/abstract/utils.js:
@noble/curves/esm/abstract/modular.js:
@noble/curves/esm/abstract/curve.js:
@noble/curves/esm/abstract/weierstrass.js:
@noble/curves/esm/_shortw_utils.js:
@noble/curves/esm/secp256k1.js:
  (*! noble-curves - MIT License (c) 2022 Paul Miller (paulmillr.com) *)
*/
