// Generated by node build.js. Edit src/, then rebuild.
// Shared, dependency-injected business logic. No client-supplied player IDs or amounts.
function createMarket(api, context) {
  const playerId = context.playerId;
  if (!playerId || !context.projectId || !context.environmentId) throw new Error('LOGIN_REQUIRED');
  const currencyId = 'COIN';
  const catalog = ['SWORD', 'REDPOTION', 'BLUEPOTION'];
  const maxRecords = 500; // Small test project ledger. Never delete paid receipt records.
  const own = (obj, key) => Object.prototype.hasOwnProperty.call(obj, key);
  const copy = x => JSON.parse(JSON.stringify(x));
  const error = message => { throw new Error(message); };
  const validId = value => typeof value === 'string' && /^[A-Za-z0-9_-]{1,100}$/.test(value);
  function checkCurrency(params) {
    if (params.currency_id && params.currency_id !== currencyId) error('INVALID_CURRENCY');
  }
  function capacity(state) {
    if (Object.keys(state.payments).length + Object.keys(state.operations).length + Object.keys(state.listings).length >= maxRecords) error('LEDGER_FULL: 관리자 확인이 필요합니다.');
  }
  async function readState() {
    const item = await api.read('state');
    if (!item || !item.writeLock || item.value.version !== 1 || !item.value.payments || !item.value.listings || !item.value.operations) error('SETUP_REQUIRED: Cloud Save simple_market/state 초기 설정을 확인하세요.');
    return item;
  }
  async function change(mutator) {
    for (let attempt = 0; attempt < 5; attempt++) {
      const record = await readState();
      const state = copy(record.value);
      const result = mutator(state);
      if (JSON.stringify(state) === JSON.stringify(record.value)) return result;
      try {
        await api.write('state', state, record.writeLock);
        return result;
      } catch (e) {
        if ((e.response && e.response.status === 409) || e.status === 409) continue;
        throw e; // Unknown write result: never start a financial side effect.
      }
    }
    error('BUSY: 다른 요청 처리 중입니다. 다시 눌러주세요.');
  }
  function listing(state, id) {
    if (!validId(id) || !own(state.listings, id)) error('LISTING_NOT_FOUND');
    return state.listings[id];
  }
  async function configuration() {
    const record = await api.read('config');
    const cfg = record && record.value;
    if (!cfg || !/^0x[0-9a-fA-F]{40}$/.test(cfg.receiverAddress) || /^0x0{40}$/i.test(cfg.receiverAddress) || !/^https:\/\//.test(cfg.rpcUrl)) error('SETUP_REQUIRED: 수신 지갑과 RPC URL을 설정하세요.');
    // A single fixed product keeps old receipts unambiguous. New pricing needs a new product version.
    if (cfg.priceWei !== '100000000000000' || cfg.goldAmount !== 10000 || !Number.isInteger(cfg.confirmations) || cfg.confirmations < 3 || cfg.confirmations > 64) error('INVALID_CONFIG: 기본 상품은 0.0001 ETH / 10000 COIN, confirmations 3 이상입니다.');
    return cfg;
  }
  function memo(product = 'GOLD') {
    const text = `UGS-${product}-v1|${context.projectId}|${context.environmentId}|${playerId}`;
    if (!/^[\x20-\x7e]+$/.test(text)) error('INVALID_CONTEXT');
    return '0x' + Array.from(text).map(c => c.charCodeAt(0).toString(16).padStart(2, '0')).join('');
  }
  function paymentStatus(p) {
    if (p.playerId !== playerId) error('WRONG_PLAYER');
    return { status: p.status === 'GRANTED' ? 'GRANTED' : 'REVIEW_REQUIRED', txHash: p.txHash, goldAmount: p.amount };
  }
  async function verifyPayment(cfg, txHash, product = 'GOLD') {
    const rpc = (method, params) => api.rpc(cfg.rpcUrl, method, params);
    const [chain, tx, receipt] = await Promise.all([
      rpc('eth_chainId', []), rpc('eth_getTransactionByHash', [txHash]), rpc('eth_getTransactionReceipt', [txHash])
    ]);
    if (BigInt(chain) !== 11155111n) error('WRONG_CHAIN');
    if (!tx) return 'RPC_TX_NOT_FOUND';
    if (!receipt || !receipt.blockNumber) return 'RPC_RECEIPT_NOT_FOUND';
    const lower = value => typeof value === 'string' ? value.toLowerCase() : '';
    const receiver = cfg.receiverAddress.toLowerCase();
    if (lower(tx.hash) !== txHash || lower(receipt.transactionHash) !== txHash || lower(tx.to) !== receiver || lower(receipt.to) !== receiver) error('INVALID_RECEIVER');
    if (!/^0x[0-9a-fA-F]{40}$/.test(tx.from) || lower(tx.from) === receiver || lower(receipt.from) !== lower(tx.from)) error('INVALID_SENDER');
    if (tx.chainId && BigInt(tx.chainId) !== 11155111n) error('WRONG_CHAIN');
    if (BigInt(tx.value) !== BigInt(cfg.priceWei)) error('INVALID_AMOUNT');
    if (lower(tx.input) !== memo(product)) error('WRONG_PLAYER: 상품 또는 게임 계정이 다른 결제입니다.');
    if (lower(tx.blockHash) !== lower(receipt.blockHash)) error('REORG_PENDING');
    const [head, block, code] = await Promise.all([
      rpc('eth_blockNumber', []), rpc('eth_getBlockByNumber', [receipt.blockNumber, false]), rpc('eth_getCode', [cfg.receiverAddress, receipt.blockNumber])
    ]);
    // This version accepts a plain receiving wallet, not a forwarding/refunding contract.
    if (code !== '0x') error('RECEIVER_MUST_BE_EOA');
    if (!block || lower(block.hash) !== lower(receipt.blockHash)) return 'RPC_BLOCK_MISMATCH';
    if (BigInt(receipt.status) !== 1n) error('TRANSACTION_FAILED');
    const count = BigInt(head) - BigInt(receipt.blockNumber) + 1n;
    return count >= BigInt(cfg.confirmations) ? null : `CONFIRMATIONS:${count}/${cfg.confirmations}`;
  }
  async function guardedEffect(effect) {
    try { await effect(); }
    catch (_) { error('REVIEW_REQUIRED: 처리 결과 확인이 필요합니다. 같은 작업을 다시 지급하지 않습니다.'); }
  }
  function serviceDiagnostic(e) {
    const body = e.response && e.response.data || {};
    const http = Number(e.response && e.response.status || e.status);
    const code = Number(body.code);
    // Only service response fields; never serialize the request or Axios exception.
    const clean = value => String(value || '').replace(/https?:\/\/\S+/gi, '[URL]')
      .replace(/Bearer\s+\S+/gi, '[TOKEN]').replace(/eyJ[A-Za-z0-9_.-]+/g, '[TOKEN]')
      .replace(/[\r\n]+/g, ' ').slice(0, 400);
    const details = Array.isArray(body.details) ? body.details.slice(0, 3).map(x =>
      typeof x === 'string' ? clean(x) : clean(x && (x.message || x.detail || x.reason))).join(' | ') : '';
    return 'HTTP_' + (Number.isInteger(http) && http > 0 ? http : 'UNKNOWN') +
      ':CODE_' + (Number.isInteger(code) && code > 0 ? code : 'UNKNOWN') +
      ':' + clean(body.title) + ':' + clean(body.detail) + ':' + details +
      (e instanceof TypeError ? ':LOCAL_TYPE_ERROR' : '');
  }
  return {
    async Sword_GetQuote() {
      const cfg = await configuration();
      capacity((await readState()).value);
      await api.requireInventoryDefinition(playerId, 'LEGENDARY_SWORD');
      const [chain, code] = await Promise.all([
        api.rpc(cfg.rpcUrl, 'eth_chainId', []), api.rpc(cfg.rpcUrl, 'eth_getCode', [cfg.receiverAddress, 'latest'])
      ]);
      if (BigInt(chain) !== 11155111n) error('WRONG_CHAIN');
      if (code !== '0x') error('RECEIVER_MUST_BE_EOA');
      return { chainId: '0xaa36a7', to: cfg.receiverAddress, value: '0x5af3107a4000', data: memo('LEGENDARY-SWORD'),
        priceEth: '0.0001', confirmations: cfg.confirmations, itemId: 'LEGENDARY_SWORD', quantity: 1 };
    },
    async Sword_Claim(params) {
      if (typeof params.tx_hash !== 'string' || !/^0x[0-9a-fA-F]{64}$/.test(params.tx_hash)) error('INVALID_TX_HASH');
      const txHash = params.tx_hash.toLowerCase();
      // Separate keys preserve compatibility with the already deployed Gold_Claim.
      const key = 'sword_' + txHash;
      // Keep the full transaction hash in the receipt and metadata, not the instance ID.
      const instanceId = txHash.slice(2, 34);
      const status = p => {
        if (p.playerId !== playerId) error('WRONG_PLAYER');
        if (p.itemId !== 'LEGENDARY_SWORD') error('INVALID_PRODUCT');
        return { status: p.status === 'GRANTED' ? 'GRANTED' : 'REVIEW_REQUIRED', txHash,
          itemId: p.itemId, quantity: 1, instanceId: p.instanceId };
      };
      const existing = (await readState()).value.payments[key];
      if (existing) {
        const result = status(existing);
        if (result.status === 'GRANTED') return result;
        // Operator-approved recovery, confirmed never received/sold/deleted on 2026-09-16.
        // Scope is one legacy receipt and one authenticated player, not a general retry.
        const approved = txHash === '0x67a8736d20780e50c421f2a282b62b26e9b11eb7d4e6f440a1cb4fdc72fbbe0d' &&
          playerId === 'py7ENhQ4WIRk8eeYVZQm3PoWP1Wq' &&
          existing.status === 'GRANTING' && !existing.recoveryStartedAt &&
          existing.instanceId === 'sword_' + txHash.slice(2);
        if (approved) {
          const cfg = await configuration();
          const reason = await verifyPayment(cfg, txHash, 'LEGENDARY-SWORD');
          if (reason) return { ...result, status: 'PENDING', pendingReason: reason };
          await api.requireInventoryDefinition(playerId, 'LEGENDARY_SWORD');
          // Fail closed on lookup failure or any existing instance.
          if (await api.getItem(playerId, existing.instanceId) || await api.getItem(playerId, instanceId))
            error('REVIEW_REQUIRED: RECOVERY_ITEM_ALREADY_EXISTS');
          const won = await change(s => {
            const p = s.payments[key];
            if (p.status !== 'GRANTING' || p.recoveryStartedAt || p.instanceId !== existing.instanceId) return false;
            p.legacyInstanceId = p.instanceId;
            p.instanceId = instanceId;
            p.recoveryStartedAt = Date.now();
            p.recoveryReason = 'OPERATOR_CONFIRMED_NEVER_RECEIVED';
            return true;
          });
          if (!won) return status((await readState()).value.payments[key]);
          let stage = 'RECOVERY_INVENTORY_ADD';
          try {
            await api.addItem(playerId, 'LEGENDARY_SWORD', instanceId, { source: 'SEPOLIA_SHOP', paymentTx: txHash });
            stage = 'RECOVERY_LEDGER_COMPLETE';
            await change(s => { s.payments[key].status = 'GRANTED'; s.payments[key].grantedAt = Date.now(); });
          } catch (e) {
            const failureCode = stage + ':' + serviceDiagnostic(e);
            try { await change(s => { s.payments[key].failureCode = failureCode; }); } catch (_) { }
            error('REVIEW_REQUIRED: ' + failureCode);
          }
          return status((await readState()).value.payments[key]);
        }
        // Read-only: a missing item may have been sold. Never automatically re-award.
        try {
          const item = await api.getItem(playerId, existing.instanceId);
          const matches = item && item.inventoryItemId === 'LEGENDARY_SWORD' &&
            item.instanceData && item.instanceData.paymentTx === txHash;
          result.pendingReason = matches ? 'INVENTORY_MATCH_FOUND' : item ? 'INVENTORY_METADATA_MISMATCH' : 'INVENTORY_INSTANCE_NOT_FOUND';
        } catch (e) { result.pendingReason = 'INVENTORY_LOOKUP_FAILED:' + serviceDiagnostic(e); }
        result.pendingReason += '; LAST=' + (existing.failureCode || 'UNKNOWN_LEGACY_FAILURE');
        return result;
      }
      const cfg = await configuration();
      const pendingReason = await verifyPayment(cfg, txHash, 'LEGENDARY-SWORD');
      if (pendingReason) return { status: 'PENDING', txHash, itemId: 'LEGENDARY_SWORD', quantity: 1, pendingReason };
      await api.requireInventoryDefinition(playerId, 'LEGENDARY_SWORD');
      const reserved = await change(s => {
        if (own(s.payments, key)) return false;
        capacity(s);
        s.payments[key] = { txHash, playerId, itemId: 'LEGENDARY_SWORD', instanceId, quantity: 1, status: 'GRANTING', createdAt: Date.now() };
        return true;
      });
      if (!reserved) return status((await readState()).value.payments[key]);
      // Exactly one reservation winner attempts the award. Ambiguous failures stay
      // GRANTING; never re-add a sword that may already have been sold or consumed.
      let stage = 'INVENTORY_ADD';
      try {
        await api.addItem(playerId, 'LEGENDARY_SWORD', instanceId, { source: 'SEPOLIA_SHOP', paymentTx: txHash });
        stage = 'LEDGER_COMPLETE';
        await change(s => { s.payments[key].status = 'GRANTED'; s.payments[key].grantedAt = Date.now(); });
      } catch (e) {
        // Numeric service codes only: no credentials, request config or headers.
        const failureCode = stage + ':' + serviceDiagnostic(e);
        try { await change(s => { s.payments[key].failureCode = failureCode; }); } catch (_) { }
        error('REVIEW_REQUIRED: ' + failureCode);
      }
      return status((await readState()).value.payments[key]);
    },
    async Gold_GetQuote() {
      const cfg = await configuration();
      capacity((await readState()).value);
      const [chain, code] = await Promise.all([
        api.rpc(cfg.rpcUrl, 'eth_chainId', []), api.rpc(cfg.rpcUrl, 'eth_getCode', [cfg.receiverAddress, 'latest'])
      ]);
      if (BigInt(chain) !== 11155111n) error('WRONG_CHAIN');
      if (code !== '0x') error('RECEIVER_MUST_BE_EOA');
      return { chainId: '0xaa36a7', to: cfg.receiverAddress, value: '0x' + BigInt(cfg.priceWei).toString(16), data: memo(), goldAmount: 10000, priceEth: '0.0001', confirmations: cfg.confirmations };
    },
    async Gold_Claim(params) {
      if (typeof params.tx_hash !== 'string' || !/^0x[0-9a-fA-F]{64}$/.test(params.tx_hash)) error('INVALID_TX_HASH');
      const txHash = params.tx_hash.toLowerCase();
      let state = (await readState()).value;
      if (own(state.payments, txHash)) return paymentStatus(state.payments[txHash]);
      const cfg = await configuration();
      const pendingReason = await verifyPayment(cfg, txHash);
      if (pendingReason) return { status: 'PENDING', txHash, goldAmount: 10000, pendingReason };
      // Validate Economy before reserving. A missing currency does not strand a receipt.
      await api.balance(playerId);
      const reserved = await change(s => {
        if (own(s.payments, txHash)) return false;
        capacity(s);
        s.payments[txHash] = { txHash, playerId, amount: 10000, status: 'GRANTING', createdAt: Date.now() };
        return true;
      });
      if (!reserved) return paymentStatus((await readState()).value.payments[txHash]);
      // Only the invocation that successfully reserved can call increment, exactly once.
      // A crash or an uncertain Economy response stays GRANTING for operator reconciliation.
      // Cloud Save + Economy are not one atomic transaction; do not claim automatic exactly-once recovery.
      await guardedEffect(async () => {
        await api.changeBalance(playerId, 10000);
        await change(s => { s.payments[txHash].status = 'GRANTED'; s.payments[txHash].grantedAt = Date.now(); });
      });
      return { status: 'GRANTED', txHash, goldAmount: 10000 };
    },
    async Mkt_GetActiveListings(params) {
      let entries = Object.values((await readState()).value.listings).filter(x => x.status === 'ACTIVE');
      if (params.sort === 'PRICE_ASC') entries.sort((a, b) => a.price - b.price);
      else if (params.sort === 'PRICE_DESC') entries.sort((a, b) => b.price - a.price);
      else entries.sort((a, b) => b.createdAt - a.createdAt);
      const limit = Number.isInteger(params.limit) ? Math.max(1, Math.min(50, params.limit)) : 30;
      return { listings: entries.slice(0, limit) };
    },
    async Mkt_CreateListing(params) {
      checkCurrency(params);
      const instanceId = params.players_inventory_item_id;
      if (!validId(instanceId) || !Number.isSafeInteger(params.price) || params.price < 1 || params.price > 1000000) error('INVALID_LISTING');
      const id = 'lst_' + Date.now().toString(36) + '_' + Math.random().toString(36).slice(2, 14);
      const item = await api.getItem(playerId, instanceId);
      if (!item || !catalog.includes(item.inventoryItemId)) error('ITEM_NOT_FOUND');
      await change(s => {
        if (own(s.listings, id) || Object.values(s.listings).some(l => l.sourceInstanceId === instanceId && l.sellerPlayerId === playerId)) error('ALREADY_LISTED');
        capacity(s);
        s.listings[id] = { listingId: id, sourceInstanceId: instanceId, status: 'CREATING', sellerPlayerId: playerId, inventoryItemId: item.inventoryItemId, instanceData: item.instanceData || {}, currencyId, price: params.price, createdAt: Date.now() };
      });
      await guardedEffect(async () => {
        await api.removeItem(playerId, item);
        await change(s => { s.listings[id].status = 'ACTIVE'; });
      });
      return { listingId: id };
    },
    async Mkt_BuyListing(params) {
      const balance = await api.balance(playerId);
      const item = await change(s => {
        const l = listing(s, params.listing_id);
        if (l.status !== 'ACTIVE') error('LISTING_NOT_ACTIVE');
        if (l.sellerPlayerId === playerId) error('CANNOT_BUY_OWN');
        if (balance.balance < l.price) error('INSUFFICIENT_GOLD');
        l.status = 'BUYING'; l.buyerPlayerId = playerId;
        return copy(l);
      });
      const instanceId = 'buy_' + item.listingId;
      await guardedEffect(async () => {
        await api.changeBalance(playerId, -item.price);
        await api.addItem(playerId, item.inventoryItemId, instanceId, item.instanceData);
        await change(s => { const l = s.listings[item.listingId]; l.status = 'SOLD'; l.soldAt = Date.now(); l.earningsStatus = 'AVAILABLE'; });
      });
      return { ok: true, newPlayersInventoryItemId: instanceId };
    },
    async Mkt_CancelListing(params) {
      const item = await change(s => {
        const l = listing(s, params.listing_id);
        if (l.sellerPlayerId !== playerId) error('SELLER_ONLY');
        if (l.status !== 'ACTIVE') error('LISTING_NOT_ACTIVE');
        l.status = 'CANCELLING'; return copy(l);
      });
      const instanceId = 'ret_' + item.listingId;
      await guardedEffect(async () => {
        await api.addItem(playerId, item.inventoryItemId, instanceId, item.instanceData);
        await change(s => { s.listings[item.listingId].status = 'CANCELLED'; });
      });
      return { ok: true, returnedPlayersInventoryItemId: instanceId };
    },
    async Mkt_ClaimEarnings(params) {
      checkCurrency(params);
      await api.balance(playerId);
      const ids = await change(s => {
        const rows = Object.values(s.listings).filter(l => l.sellerPlayerId === playerId && l.status === 'SOLD' && l.earningsStatus === 'AVAILABLE');
        rows.forEach(l => { l.earningsStatus = 'CLAIMING'; });
        return rows.map(l => ({ id: l.listingId, price: l.price }));
      });
      const total = ids.reduce((sum, l) => sum + l.price, 0);
      if (!total) return { ok: true, claimed: 0 };
      await guardedEffect(async () => {
        await api.changeBalance(playerId, total);
        await change(s => { ids.forEach(l => { s.listings[l.id].earningsStatus = 'CLAIMED'; }); });
      });
      return { ok: true, claimed: total };
    },
    async Mkt_Gacha(params) {
      if (typeof params.request_id !== 'string' || !/^[a-f0-9]{32}$/.test(params.request_id)) error('INVALID_REQUEST_ID');
      const id = 'g_' + playerId + '_' + params.request_id;
      const previous = (await readState()).value.operations[id];
      if (previous) {
        if (previous.status !== 'DONE') error('REVIEW_REQUIRED');
        return { ok: true, inventoryItemId: previous.itemId };
      }
      if ((await api.balance(playerId)).balance < 100) error('INSUFFICIENT_GOLD');
      const itemId = catalog[Math.floor(Math.random() * catalog.length)];
      await change(s => {
        if (own(s.operations, id)) error('ALREADY_REQUESTED');
        capacity(s);
        s.operations[id] = { playerId, itemId, status: 'GRANTING', createdAt: Date.now() };
      });
      await guardedEffect(async () => {
        await api.changeBalance(playerId, -100);
        await api.addItem(playerId, itemId, id, {});
        await change(s => { s.operations[id].status = 'DONE'; });
      });
      return { ok: true, inventoryItemId: itemId };
    }
  };
}

if (typeof module !== 'undefined') module.exports = { createMarket };

function createAdapter(context) {
  const { DataApi } = require('@unity-services/cloud-save-1.4');
  const { ConfigurationApi, CurrenciesApi, InventoryApi } = require('@unity-services/economy-2.5');
  const axios = require('axios-1.6');
  // Service authority is needed after the player Economy write policy is applied.
  const auth = { ...context, accessToken: context.serviceToken };
  const save = new DataApi(auth);
  const config = new ConfigurationApi(auth);
  const currency = new CurrenciesApi(auth);
  const inventory = new InventoryApi(auth);
  const projectId = context.projectId;
  const hashes = {};
  async function playerArgs(playerId) {
    if (!hashes[playerId]) {
      const response = await config.getPlayerConfiguration({ projectId, playerId });
      hashes[playerId] = response.data.metadata.configAssignmentHash;
    }
    return { projectId, playerId, configAssignmentHash: hashes[playerId] };
  }
  return {
    async requireInventoryDefinition(playerId, itemId) {
      const response = await config.getPlayerConfiguration({ projectId, playerId });
      hashes[playerId] = response.data.metadata.configAssignmentHash;
      if (!(response.data.results || []).some(item => item.id === itemId && item.type === 'INVENTORY_ITEM'))
        throw new Error('SETUP_REQUIRED: LEGENDARY_SWORD Inventory Item을 같은 환경에 Publish하세요.');
    },
    async read(key) {
      const response = await save.getCustomItems(projectId, 'simple_market', [key]);
      const item = (response.data.results || []).find(x => x.key === key);
      return item ? { value: item.value, writeLock: item.writeLock } : null;
    },
    async write(key, value, writeLock) {
      if (!writeLock) throw new Error('SETUP_REQUIRED: state must be created in Dashboard first.');
      await save.setCustomItem(projectId, 'simple_market', { key, value, writeLock });
    },
    async rpc(url, method, params) {
      // Never log axios errors: their request config may contain a private RPC URL.
      try {
        const response = await axios.post(url, { jsonrpc: '2.0', id: 1, method, params }, { timeout: 4500 });
        if (response.data.error || !Object.prototype.hasOwnProperty.call(response.data, 'result')) throw new Error();
        return response.data.result;
      } catch (_) { throw new Error('RPC_UNAVAILABLE: 잠시 후 결제 확인을 다시 누르세요.'); }
    },
    async balance(playerId) {
      const response = await currency.getPlayerCurrencies(await playerArgs(playerId));
      const coin = (response.data.results || []).find(x => x.currencyId === 'COIN');
      if (!coin) throw new Error('SETUP_REQUIRED: COIN 통화를 Publish하고 잔액을 조회하세요.');
      return coin;
    },
    async changeBalance(playerId, amount) {
      const method = amount > 0 ? 'incrementPlayerCurrencyBalance' : 'decrementPlayerCurrencyBalance';
      await currency[method]({ ...await playerArgs(playerId), currencyId: 'COIN', currencyModifyBalanceRequest: { amount: Math.abs(amount) } });
    },
    async getItem(playerId, instanceId) {
      const args = await playerArgs(playerId);
      try {
        const response = await inventory.getPlayerInventory({ ...args, playersInventoryItemIds: [instanceId] });
        return (response.data.results || []).find(x => x.playersInventoryItemId === instanceId);
      } catch (e) {
        if (Number(e.response && e.response.status || e.status) !== 400) throw e;
      }
      // Legacy receipt IDs may be rejected as a query filter. Read pages instead.
      // This is read-only and never interprets an incomplete scan as a missing item.
      let after;
      for (let page = 0; page < 20; page++) {
        const response = await inventory.getPlayerInventory({ ...args, limit: 100, ...(after ? { after } : {}) });
        const items = response.data.results || [];
        const found = items.find(x => x.playersInventoryItemId === instanceId);
        if (found) return found;
        if (!(response.data.links && response.data.links.next)) return undefined;
        const next = items.length && items[items.length - 1].playersInventoryItemId;
        if (!next || next === after) throw new Error('INVENTORY_SCAN_INCOMPLETE');
        after = next;
      }
      throw new Error('INVENTORY_SCAN_INCOMPLETE');
    },
    async removeItem(playerId, item) {
      await inventory.deleteInventoryItem({ ...await playerArgs(playerId), playersInventoryItemId: item.playersInventoryItemId, writeLock: item.writeLock, inventoryDeleteRequest: {} });
    },
    async addItem(playerId, itemId, instanceId, data) {
      await inventory.addInventoryItem({ ...await playerArgs(playerId), addInventoryRequest: { inventoryItemId: itemId, playersInventoryItemId: instanceId, instanceData: data || {} } });
    }
  };
}

module.exports = async (args) => createMarket(createAdapter(args.context), args.context).Mkt_CreateListing(args.params || {});
module.exports.params = {
  "players_inventory_item_id": {
    "type": "String",
    "required": true
  },
  "price": {
    "type": "Numeric",
    "required": true
  },
  "currency_id": {
    "type": "String",
    "required": false
  }
};
