// ECONOMY-FREE V2. Generated by node build.js. Edit src/, then rebuild.
// Shared, dependency-injected business logic. No client-supplied player IDs or amounts.
function createMarket(api, context) {
  const playerId = context.playerId;
  if (!playerId || !context.projectId || !context.environmentId) throw new Error('LOGIN_REQUIRED');
  const currencyId = 'COIN';
  const catalog = ['SWORD', 'REDPOTION', 'BLUEPOTION'];
  const maxRecords = 500; // Small test project ledger. Never delete paid receipt records.
  const own = (obj, key) => Object.prototype.hasOwnProperty.call(obj, key);
  const copy = x => JSON.parse(JSON.stringify(x));
  const error = message => { throw new Error(message); };
  const validId = value => typeof value === 'string' && /^[A-Za-z0-9_-]{1,100}$/.test(value);
  function checkCurrency(params) {
    if (params.currency_id && params.currency_id !== currencyId) error('INVALID_CURRENCY');
  }
  function capacity(state) {
    if (api.grantPayment) {
      if (Buffer.byteLength(JSON.stringify(state), 'utf8') > 3800000) error('LEDGER_FULL');
      return;
    }
    if (Object.keys(state.payments).length + Object.keys(state.operations).length + Object.keys(state.listings).length >= maxRecords) error('LEDGER_FULL: 관리자 확인이 필요합니다.');
  }
  async function readState() {
    const item = await api.read('state');
    if (!item || !item.writeLock || item.value.version !== 1 || !item.value.payments || !item.value.listings || !item.value.operations) error('SETUP_REQUIRED: Cloud Save simple_market/state 초기 설정을 확인하세요.');
    return item;
  }
  async function change(mutator) {
    for (let attempt = 0; attempt < 5; attempt++) {
      const record = await readState();
      const state = copy(record.value);
      const result = mutator(state);
      if (JSON.stringify(state) === JSON.stringify(record.value)) return result;
      try {
        await api.write('state', state, record.writeLock);
        return result;
      } catch (e) {
        if ((e.response && e.response.status === 409) || e.status === 409) continue;
        throw e; // Unknown write result: never start a financial side effect.
      }
    }
    error('BUSY: 다른 요청 처리 중입니다. 다시 눌러주세요.');
  }
  function listing(state, id) {
    if (!validId(id) || !own(state.listings, id)) error('LISTING_NOT_FOUND');
    return state.listings[id];
  }
  async function configuration() {
    const record = await api.read('config');
    const cfg = record && record.value;
    if (!cfg || !/^0x[0-9a-fA-F]{40}$/.test(cfg.receiverAddress) || /^0x0{40}$/i.test(cfg.receiverAddress) || !/^https:\/\//.test(cfg.rpcUrl)) error('SETUP_REQUIRED: 수신 지갑과 RPC URL을 설정하세요.');
    // A single fixed product keeps old receipts unambiguous. New pricing needs a new product version.
    if (cfg.priceWei !== '100000000000000' || cfg.goldAmount !== 10000 || !Number.isInteger(cfg.confirmations) || cfg.confirmations < 3 || cfg.confirmations > 64) error('INVALID_CONFIG: 기본 상품은 0.0001 ETH / 10000 COIN, confirmations 3 이상입니다.');
    return cfg;
  }
  function memo(product = 'GOLD') {
    const text = `UGS-${product}-v1|${context.projectId}|${context.environmentId}|${playerId}`;
    if (!/^[\x20-\x7e]+$/.test(text)) error('INVALID_CONTEXT');
    return '0x' + Array.from(text).map(c => c.charCodeAt(0).toString(16).padStart(2, '0')).join('');
  }
  function paymentStatus(p) {
    if (p.playerId !== playerId) error('WRONG_PLAYER');
    return { status: p.status === 'GRANTED' ? 'GRANTED' : 'REVIEW_REQUIRED', txHash: p.txHash, goldAmount: p.amount };
  }
  async function verifyPayment(cfg, txHash, product = 'GOLD') {
    const rpc = (method, params) => api.rpc(cfg.rpcUrl, method, params);
    const [chain, tx, receipt] = await Promise.all([
      rpc('eth_chainId', []), rpc('eth_getTransactionByHash', [txHash]), rpc('eth_getTransactionReceipt', [txHash])
    ]);
    if (BigInt(chain) !== 11155111n) error('WRONG_CHAIN');
    if (!tx) return 'RPC_TX_NOT_FOUND';
    if (!receipt || !receipt.blockNumber) return 'RPC_RECEIPT_NOT_FOUND';
    const lower = value => typeof value === 'string' ? value.toLowerCase() : '';
    const receiver = cfg.receiverAddress.toLowerCase();
    if (lower(tx.hash) !== txHash || lower(receipt.transactionHash) !== txHash || lower(tx.to) !== receiver || lower(receipt.to) !== receiver) error('INVALID_RECEIVER');
    if (!/^0x[0-9a-fA-F]{40}$/.test(tx.from) || lower(tx.from) === receiver || lower(receipt.from) !== lower(tx.from)) error('INVALID_SENDER');
    if (tx.chainId && BigInt(tx.chainId) !== 11155111n) error('WRONG_CHAIN');
    if (BigInt(tx.value) !== BigInt(cfg.priceWei)) error('INVALID_AMOUNT');
    if (lower(tx.input) !== memo(product)) error('WRONG_PLAYER: 상품 또는 게임 계정이 다른 결제입니다.');
    if (lower(tx.blockHash) !== lower(receipt.blockHash)) error('REORG_PENDING');
    const [head, block, code] = await Promise.all([
      rpc('eth_blockNumber', []), rpc('eth_getBlockByNumber', [receipt.blockNumber, false]), rpc('eth_getCode', [cfg.receiverAddress, receipt.blockNumber])
    ]);
    // This version accepts a plain receiving wallet, not a forwarding/refunding contract.
    if (code !== '0x') error('RECEIVER_MUST_BE_EOA');
    if (!block || lower(block.hash) !== lower(receipt.blockHash)) return 'RPC_BLOCK_MISMATCH';
    if (BigInt(receipt.status) !== 1n) error('TRANSACTION_FAILED');
    const count = BigInt(head) - BigInt(receipt.blockNumber) + 1n;
    return count >= BigInt(cfg.confirmations) ? null : `CONFIRMATIONS:${count}/${cfg.confirmations}`;
  }
  async function guardedEffect(effect) {
    try { await effect(); }
    catch (_) { error('REVIEW_REQUIRED: 처리 결과 확인이 필요합니다. 같은 작업을 다시 지급하지 않습니다.'); }
  }
  function serviceDiagnostic(e) {
    const body = e.response && e.response.data || {};
    const http = Number(e.response && e.response.status || e.status);
    const code = Number(body.code);
    // Only service response fields; never serialize the request or Axios exception.
    const clean = value => String(value || '').replace(/https?:\/\/\S+/gi, '[URL]')
      .replace(/Bearer\s+\S+/gi, '[TOKEN]').replace(/eyJ[A-Za-z0-9_.-]+/g, '[TOKEN]')
      .replace(/[\r\n]+/g, ' ').slice(0, 400);
    const details = Array.isArray(body.details) ? body.details.slice(0, 3).map(x =>
      typeof x === 'string' ? clean(x) : clean(x && (x.message || x.detail || x.reason))).join(' | ') : '';
    return 'HTTP_' + (Number.isInteger(http) && http > 0 ? http : 'UNKNOWN') +
      ':CODE_' + (Number.isInteger(code) && code > 0 ? code : 'UNKNOWN') +
      ':' + clean(body.title) + ':' + clean(body.detail) + ':' + details +
      (e instanceof TypeError ? ':LOCAL_TYPE_ERROR' : '');
  }
  return {
    async Sword_GetQuote() {
      const cfg = await configuration();
      capacity((await readState()).value);
      await api.requireInventoryDefinition(playerId, 'LEGENDARY_SWORD');
      const [chain, code] = await Promise.all([
        api.rpc(cfg.rpcUrl, 'eth_chainId', []), api.rpc(cfg.rpcUrl, 'eth_getCode', [cfg.receiverAddress, 'latest'])
      ]);
      if (BigInt(chain) !== 11155111n) error('WRONG_CHAIN');
      if (code !== '0x') error('RECEIVER_MUST_BE_EOA');
      return { chainId: '0xaa36a7', to: cfg.receiverAddress, value: '0x5af3107a4000', data: memo('LEGENDARY-SWORD'),
        priceEth: '0.0001', confirmations: cfg.confirmations, itemId: 'LEGENDARY_SWORD', quantity: 1 };
    },
    async Sword_Claim(params) {
      if (typeof params.tx_hash !== 'string' || !/^0x[0-9a-fA-F]{64}$/.test(params.tx_hash)) error('INVALID_TX_HASH');
      const txHash = params.tx_hash.toLowerCase();
      // Separate keys preserve compatibility with the already deployed Gold_Claim.
      const key = 'sword_' + txHash;
      // Keep the full transaction hash in the receipt and metadata, not the instance ID.
      const instanceId = txHash.slice(2, 34);
      const status = p => {
        if (p.playerId !== playerId) error('WRONG_PLAYER');
        if (p.itemId !== 'LEGENDARY_SWORD') error('INVALID_PRODUCT');
        return { status: p.status === 'GRANTED' ? 'GRANTED' : 'REVIEW_REQUIRED', txHash,
          itemId: p.itemId, quantity: 1, instanceId: p.instanceId };
      };
      const existing = (await readState()).value.payments[key];
      if (existing) {
        const result = status(existing);
        if (result.status === 'GRANTED') return result;
        // Operator-approved recovery, confirmed never received/sold/deleted on 2026-09-16.
        // Scope is one legacy receipt and one authenticated player, not a general retry.
        const approved = txHash === '0x67a8736d20780e50c421f2a282b62b26e9b11eb7d4e6f440a1cb4fdc72fbbe0d' &&
          playerId === 'py7ENhQ4WIRk8eeYVZQm3PoWP1Wq' &&
          existing.status === 'GRANTING' && !existing.recoveryStartedAt &&
          existing.instanceId === 'sword_' + txHash.slice(2);
        if (approved) {
          const cfg = await configuration();
          const reason = await verifyPayment(cfg, txHash, 'LEGENDARY-SWORD');
          if (reason) return { ...result, status: 'PENDING', pendingReason: reason };
          await api.requireInventoryDefinition(playerId, 'LEGENDARY_SWORD');
          // Fail closed on lookup failure or any existing instance.
          if (await api.getItem(playerId, existing.instanceId) || await api.getItem(playerId, instanceId))
            error('REVIEW_REQUIRED: RECOVERY_ITEM_ALREADY_EXISTS');
          const won = await change(s => {
            const p = s.payments[key];
            if (p.status !== 'GRANTING' || p.recoveryStartedAt || p.instanceId !== existing.instanceId) return false;
            p.legacyInstanceId = p.instanceId;
            p.instanceId = instanceId;
            p.recoveryStartedAt = Date.now();
            p.recoveryReason = 'OPERATOR_CONFIRMED_NEVER_RECEIVED';
            return true;
          });
          if (!won) return status((await readState()).value.payments[key]);
          let stage = 'RECOVERY_INVENTORY_ADD';
          try {
            await api.addItem(playerId, 'LEGENDARY_SWORD', instanceId, { source: 'SEPOLIA_SHOP', paymentTx: txHash });
            stage = 'RECOVERY_LEDGER_COMPLETE';
            await change(s => { s.payments[key].status = 'GRANTED'; s.payments[key].grantedAt = Date.now(); });
          } catch (e) {
            const failureCode = stage + ':' + serviceDiagnostic(e);
            try { await change(s => { s.payments[key].failureCode = failureCode; }); } catch (_) { }
            error('REVIEW_REQUIRED: ' + failureCode);
          }
          return status((await readState()).value.payments[key]);
        }
        // Read-only: a missing item may have been sold. Never automatically re-award.
        try {
          const item = await api.getItem(playerId, existing.instanceId);
          const matches = item && item.inventoryItemId === 'LEGENDARY_SWORD' &&
            item.instanceData && item.instanceData.paymentTx === txHash;
          result.pendingReason = matches ? 'INVENTORY_MATCH_FOUND' : item ? 'INVENTORY_METADATA_MISMATCH' : 'INVENTORY_INSTANCE_NOT_FOUND';
        } catch (e) { result.pendingReason = 'INVENTORY_LOOKUP_FAILED:' + serviceDiagnostic(e); }
        result.pendingReason += '; LAST=' + (existing.failureCode || 'UNKNOWN_LEGACY_FAILURE');
        return result;
      }
      const cfg = await configuration();
      const pendingReason = await verifyPayment(cfg, txHash, 'LEGENDARY-SWORD');
      if (pendingReason) return { status: 'PENDING', txHash, itemId: 'LEGENDARY_SWORD', quantity: 1, pendingReason };
      await api.requireInventoryDefinition(playerId, 'LEGENDARY_SWORD');
      if (api.grantPayment) return api.grantPayment({ key, txHash, playerId, itemId: 'LEGENDARY_SWORD', instanceId });
      const reserved = await change(s => {
        if (own(s.payments, key)) return false;
        capacity(s);
        s.payments[key] = { txHash, playerId, itemId: 'LEGENDARY_SWORD', instanceId, quantity: 1, status: 'GRANTING', createdAt: Date.now() };
        return true;
      });
      if (!reserved) return status((await readState()).value.payments[key]);
      // Exactly one reservation winner attempts the award. Ambiguous failures stay
      // GRANTING; never re-add a sword that may already have been sold or consumed.
      let stage = 'INVENTORY_ADD';
      try {
        await api.addItem(playerId, 'LEGENDARY_SWORD', instanceId, { source: 'SEPOLIA_SHOP', paymentTx: txHash });
        stage = 'LEDGER_COMPLETE';
        await change(s => { s.payments[key].status = 'GRANTED'; s.payments[key].grantedAt = Date.now(); });
      } catch (e) {
        // Numeric service codes only: no credentials, request config or headers.
        const failureCode = stage + ':' + serviceDiagnostic(e);
        try { await change(s => { s.payments[key].failureCode = failureCode; }); } catch (_) { }
        error('REVIEW_REQUIRED: ' + failureCode);
      }
      return status((await readState()).value.payments[key]);
    },
    async Gold_GetQuote() {
      const cfg = await configuration();
      capacity((await readState()).value);
      const [chain, code] = await Promise.all([
        api.rpc(cfg.rpcUrl, 'eth_chainId', []), api.rpc(cfg.rpcUrl, 'eth_getCode', [cfg.receiverAddress, 'latest'])
      ]);
      if (BigInt(chain) !== 11155111n) error('WRONG_CHAIN');
      if (code !== '0x') error('RECEIVER_MUST_BE_EOA');
      return { chainId: '0xaa36a7', to: cfg.receiverAddress, value: '0x' + BigInt(cfg.priceWei).toString(16), data: memo(), goldAmount: 10000, priceEth: '0.0001', confirmations: cfg.confirmations };
    },
    async Gold_Claim(params) {
      if (typeof params.tx_hash !== 'string' || !/^0x[0-9a-fA-F]{64}$/.test(params.tx_hash)) error('INVALID_TX_HASH');
      const txHash = params.tx_hash.toLowerCase();
      let state = (await readState()).value;
      if (own(state.payments, txHash)) return paymentStatus(state.payments[txHash]);
      const cfg = await configuration();
      const pendingReason = await verifyPayment(cfg, txHash);
      if (pendingReason) return { status: 'PENDING', txHash, goldAmount: 10000, pendingReason };
      // Validate Economy before reserving. A missing currency does not strand a receipt.
      await api.balance(playerId);
      if (api.grantPayment) return api.grantPayment({ key: txHash, txHash, playerId, amount: 10000 });
      const reserved = await change(s => {
        if (own(s.payments, txHash)) return false;
        capacity(s);
        s.payments[txHash] = { txHash, playerId, amount: 10000, status: 'GRANTING', createdAt: Date.now() };
        return true;
      });
      if (!reserved) return paymentStatus((await readState()).value.payments[txHash]);
      // Only the invocation that successfully reserved can call increment, exactly once.
      // A crash or an uncertain Economy response stays GRANTING for operator reconciliation.
      // Cloud Save + Economy are not one atomic transaction; do not claim automatic exactly-once recovery.
      await guardedEffect(async () => {
        await api.changeBalance(playerId, 10000);
        await change(s => { s.payments[txHash].status = 'GRANTED'; s.payments[txHash].grantedAt = Date.now(); });
      });
      return { status: 'GRANTED', txHash, goldAmount: 10000 };
    },
    async Mkt_GetActiveListings(params) {
      let entries = Object.values((await readState()).value.listings).filter(x => x.status === 'ACTIVE');
      if (params.sort === 'PRICE_ASC') entries.sort((a, b) => a.price - b.price);
      else if (params.sort === 'PRICE_DESC') entries.sort((a, b) => b.price - a.price);
      else entries.sort((a, b) => b.createdAt - a.createdAt);
      const limit = Number.isInteger(params.limit) ? Math.max(1, Math.min(50, params.limit)) : 30;
      return { listings: entries.slice(0, limit) };
    },
    async Mkt_CreateListing(params) {
      checkCurrency(params);
      const instanceId = params.players_inventory_item_id;
      if (!validId(instanceId) || !Number.isSafeInteger(params.price) || params.price < 1 || params.price > 1000000) error('INVALID_LISTING');
      const id = 'lst_' + Date.now().toString(36) + '_' + Math.random().toString(36).slice(2, 14);
      const item = await api.getItem(playerId, instanceId);
      if (!item || !catalog.includes(item.inventoryItemId)) error('ITEM_NOT_FOUND');
      await change(s => {
        if (own(s.listings, id) || Object.values(s.listings).some(l => l.sourceInstanceId === instanceId && l.sellerPlayerId === playerId)) error('ALREADY_LISTED');
        capacity(s);
        s.listings[id] = { listingId: id, sourceInstanceId: instanceId, status: 'CREATING', sellerPlayerId: playerId, inventoryItemId: item.inventoryItemId, instanceData: item.instanceData || {}, currencyId, price: params.price, createdAt: Date.now() };
      });
      await guardedEffect(async () => {
        await api.removeItem(playerId, item);
        await change(s => { s.listings[id].status = 'ACTIVE'; });
      });
      return { listingId: id };
    },
    async Mkt_BuyListing(params) {
      const balance = await api.balance(playerId);
      const item = await change(s => {
        const l = listing(s, params.listing_id);
        if (l.status !== 'ACTIVE') error('LISTING_NOT_ACTIVE');
        if (l.sellerPlayerId === playerId) error('CANNOT_BUY_OWN');
        if (balance.balance < l.price) error('INSUFFICIENT_GOLD');
        l.status = 'BUYING'; l.buyerPlayerId = playerId;
        return copy(l);
      });
      const instanceId = 'buy_' + item.listingId;
      await guardedEffect(async () => {
        await api.changeBalance(playerId, -item.price);
        await api.addItem(playerId, item.inventoryItemId, instanceId, item.instanceData);
        await change(s => { const l = s.listings[item.listingId]; l.status = 'SOLD'; l.soldAt = Date.now(); l.earningsStatus = 'AVAILABLE'; });
      });
      return { ok: true, newPlayersInventoryItemId: instanceId };
    },
    async Mkt_CancelListing(params) {
      const item = await change(s => {
        const l = listing(s, params.listing_id);
        if (l.sellerPlayerId !== playerId) error('SELLER_ONLY');
        if (l.status !== 'ACTIVE') error('LISTING_NOT_ACTIVE');
        l.status = 'CANCELLING'; return copy(l);
      });
      const instanceId = 'ret_' + item.listingId;
      await guardedEffect(async () => {
        await api.addItem(playerId, item.inventoryItemId, instanceId, item.instanceData);
        await change(s => { s.listings[item.listingId].status = 'CANCELLED'; });
      });
      return { ok: true, returnedPlayersInventoryItemId: instanceId };
    },
    async Mkt_ClaimEarnings(params) {
      checkCurrency(params);
      await api.balance(playerId);
      const ids = await change(s => {
        const rows = Object.values(s.listings).filter(l => l.sellerPlayerId === playerId && l.status === 'SOLD' && l.earningsStatus === 'AVAILABLE');
        rows.forEach(l => { l.earningsStatus = 'CLAIMING'; });
        return rows.map(l => ({ id: l.listingId, price: l.price }));
      });
      const total = ids.reduce((sum, l) => sum + l.price, 0);
      if (!total) return { ok: true, claimed: 0 };
      await guardedEffect(async () => {
        await api.changeBalance(playerId, total);
        await change(s => { ids.forEach(l => { s.listings[l.id].earningsStatus = 'CLAIMED'; }); });
      });
      return { ok: true, claimed: total };
    },
    async Mkt_Gacha(params) {
      if (typeof params.request_id !== 'string' || !/^[a-f0-9]{32}$/.test(params.request_id)) error('INVALID_REQUEST_ID');
      const id = 'g_' + playerId + '_' + params.request_id;
      const previous = (await readState()).value.operations[id];
      if (previous) {
        if (previous.status !== 'DONE') error('REVIEW_REQUIRED');
        return { ok: true, inventoryItemId: previous.itemId };
      }
      if ((await api.balance(playerId)).balance < 100) error('INSUFFICIENT_GOLD');
      const itemId = catalog[Math.floor(Math.random() * catalog.length)];
      await change(s => {
        if (own(s.operations, id)) error('ALREADY_REQUESTED');
        capacity(s);
        s.operations[id] = { playerId, itemId, status: 'GRANTING', createdAt: Date.now() };
      });
      await guardedEffect(async () => {
        await api.changeBalance(playerId, -100);
        await api.addItem(playerId, itemId, id, {});
        await change(s => { s.operations[id].status = 'DONE'; });
      });
      return { ok: true, inventoryItemId: itemId };
    }
  };
}

if (typeof module !== 'undefined') module.exports = { createMarket };

// Classroom ledger: one private value, one compare-and-swap per transaction.
// Keep receipts permanently. Provision state in Dashboard; never create it in a race.
function createCloudStore(storage) {
  const clone = x => JSON.parse(JSON.stringify(x));
  const own = (o, k) => Object.prototype.hasOwnProperty.call(o, k);
  async function read() {
    const row = await storage.readLedger();
    if (!row?.writeLock || row.value?.version !== 2 || !Number.isSafeInteger(row.value.revision) || row.value.revision < 0 || !row.value.players || !row.value.listings || !row.value.operations || !row.value.payments)
      throw Error('SETUP_REQUIRED: classroom_market / Private / state v2');
    return row;
  }
  function player(s, id) {
    if (!/^[A-Za-z0-9_-]{1,100}$/.test(id) || ['__proto__', 'constructor', 'prototype'].includes(id)) throw Error('INVALID_PLAYER');
    if (!own(s.players, id)) {
      if (Object.keys(s.players).length >= 200) throw Error('CLASSROOM_FULL');
      s.players[id] = { balance: 1000, items: {} };
    }
    return s.players[id];
  }
  function credit(p, amount) {
    if (!Number.isSafeInteger(amount) || !Number.isSafeInteger(p.balance + amount)) throw Error('INVALID_AMOUNT');
    if (p.balance + amount < 0) throw Error('INSUFFICIENT_GOLD');
    p.balance += amount;
  }
  async function change(fn) {
    for (let attempt = 0; attempt < 8; attempt++) {
      const row = await read(), state = clone(row.value);
      const result = fn(state);
      if (JSON.stringify(state) === JSON.stringify(row.value)) return result;
      state.revision = (state.revision || 0) + 1;
      if (Buffer.byteLength(JSON.stringify(state), 'utf8') > 4000000) throw Error('LEDGER_FULL');
      try { await storage.writeLedger(state, row.writeLock); return result; }
      catch (e) {
        if (Number(e.response?.status || e.status) !== 409) throw e;
      }
    }
    throw Error('BUSY: retry the same request');
  }
  return { read, change, player, credit };
}
if (typeof module !== 'undefined') module.exports = { createCloudStore };

function createCloudAdapter(context) {
  const { DataApi } = require('@unity-services/cloud-save-1.4');
  const axios = require('axios-1.6');
  if (!context.serviceToken) throw Error('SERVER_AUTH_REQUIRED');
  const save = new DataApi({ ...context, accessToken: context.serviceToken });
  const project = context.projectId;
  const makeStore = typeof createCloudStore === 'function' ? createCloudStore : require('./cloud-store').createCloudStore;
  const store = makeStore({
    async readLedger() {
      const r = await save.getPrivateCustomItems(project, 'classroom_market', ['state']);
      return r.data.results.find(x => x.key === 'state');
    },
    async writeLedger(value, writeLock) {
      await save.setPrivateCustomItem(project, 'classroom_market', { key: 'state', value, writeLock });
    }
  });
  const catalog = ['SWORD', 'REDPOTION', 'BLUEPOTION', 'LEGENDARY_SWORD', 'MYTHIC_SWORD_NFT'];
  return {
    store,
    async read(key) {
      if (key === 'state') {
        const r = await store.read();
        const legacy = await save.getCustomItems(project, 'simple_market', ['state']);
        const old = legacy.data.results.find(x => x.key === 'state')?.value?.payments || {};
        const payments = Object.fromEntries(Object.entries(old).map(([k, v]) => [k, { ...v, status: 'MIGRATION_REQUIRED' }]));
        // Compatibility view for the existing, tested Sepolia verifier only.
        return { ...r, value: { ...r.value, payments: { ...payments, ...r.value.payments }, version: 1 } };
      }
      const r = await save.getCustomItems(project, 'simple_market', [key]);
      return r.data.results.find(x => x.key === key);
    },
    async write(key, value, writeLock) {
      if (key === 'state') throw Error('USE_ATOMIC_LEDGER');
      if (!writeLock) throw Error('SETUP_REQUIRED');
      await save.setCustomItem(project, 'simple_market', { key, value, writeLock });
    },
    async rpc(url, method, params) {
      try {
        const r = await axios.post(url, { jsonrpc: '2.0', id: 1, method, params }, { timeout: 4500 });
        if (r.data.error || !Object.prototype.hasOwnProperty.call(r.data, 'result')) throw Error();
        return r.data.result;
      } catch (_) { throw Error('RPC_UNAVAILABLE'); }
    },
    async requireInventoryDefinition(playerId, itemId) {
      if (!catalog.includes(itemId)) throw Error('INVALID_ITEM');
    },
    async balance(id) {
      return store.change(s => ({ currencyId: 'COIN', balance: store.player(s, id).balance }));
    },
    async inventory(id) {
      return store.change(s => Object.values(store.player(s, id).items));
    },
    async getItem(id, instance) { return (await this.inventory(id)).find(x => x.playersInventoryItemId === instance); },
    async addItem(id, itemId, instance, data) {
      if (!catalog.includes(itemId)) throw Error('INVALID_ITEM');
      return store.change(s => {
        const p = store.player(s, id), old = p.items[instance];
        if (old) {
          if (old.inventoryItemId !== itemId || JSON.stringify(old.instanceData) !== JSON.stringify(data || {})) throw Error('ITEM_CONFLICT');
          return;
        }
        p.items[instance] = { inventoryItemId: itemId, playersInventoryItemId: instance, instanceData: data || {} };
      });
    },
    async removeItem(id, item) {
      return store.change(s => { delete store.player(s, id).items[item.playersInventoryItemId]; });
    },
    async grantPayment({ key, txHash, playerId, itemId, instanceId, amount }) {
      return store.change(s => {
        const old = s.payments[key];
        if (old) {
          if (old.playerId !== playerId) throw Error('WRONG_PLAYER');
          if (old.status !== 'GRANTED') throw Error('REVIEW_REQUIRED');
        } else {
          const p = store.player(s, playerId);
          if (itemId) p.items[instanceId] = { inventoryItemId: itemId, playersInventoryItemId: instanceId, instanceData: { source: 'SEPOLIA_SHOP', paymentTx: txHash } };
          else store.credit(p, amount);
          s.payments[key] = { playerId, txHash, itemId, instanceId, amount, status: 'GRANTED', grantedAt: Date.now() };
        }
        return itemId ? { status: 'GRANTED', txHash, itemId, instanceId, quantity: 1 } : { status: 'GRANTED', txHash, goldAmount: amount };
      });
    }
  };
}
if (typeof module !== 'undefined') module.exports = { createCloudAdapter };

function createCloudMarket(api, context) {
  const legacyPayments = createMarket(api, context);
  const { store } = api, pid = context.playerId;
  const own = (o, k) => Object.prototype.hasOwnProperty.call(o, k);
  const fail = code => { throw Error(code); };
  const catalog = ['SWORD', 'REDPOTION', 'BLUEPOTION'];
  const tradable = [...catalog, 'LEGENDARY_SWORD'];
  const id = x => typeof x === 'string' && /^[A-Za-z0-9_-]{1,100}$/.test(x) && !['__proto__', 'constructor', 'prototype'].includes(x);
  const currency = p => { if (p.currency_id && p.currency_id !== 'COIN') fail('INVALID_CURRENCY'); };
  function listing(s, key) { if (!id(key) || !own(s.listings, key)) fail('LISTING_NOT_FOUND'); return s.listings[key]; }
  function request(params, kind, fn) {
    if (!id(params.request_id)) fail('INVALID_REQUEST_ID');
    const key = pid + ':' + params.request_id;
    const signature = JSON.stringify([kind, params.players_inventory_item_id, params.price, params.listing_id]);
    return store.change(s => {
      if (own(s.operations, key)) {
        if (s.operations[key].signature !== signature) fail('REQUEST_ID_REUSED');
        return s.operations[key].result;
      }
      const result = fn(s, store.player(s, pid));
      s.operations[key] = { signature, result };
      return result;
    });
  }
  return {
    Sword_GetQuote: legacyPayments.Sword_GetQuote,
    Sword_Claim: legacyPayments.Sword_Claim,
    Gold_GetQuote: legacyPayments.Gold_GetQuote,
    Gold_Claim: legacyPayments.Gold_Claim,
    async Mkt_GetPlayer() {
      return store.change(s => { const p = store.player(s, pid); return { balance: p.balance, items: Object.values(p.items) }; });
    },
    async Mkt_GetActiveListings(params) {
      const s = (await store.read()).value;
      let rows = Object.values(s.listings).filter(x => x.status === 'ACTIVE');
      rows.sort(params.sort === 'PRICE_ASC' ? (a,b) => a.price-b.price : params.sort === 'PRICE_DESC' ? (a,b) => b.price-a.price : (a,b) => b.createdAt-a.createdAt);
      const limit = Number.isInteger(params.limit) ? Math.max(1, Math.min(100, params.limit)) : 30;
      // Never expose wallets, receipts, private inventories or the whole ledger.
      return { revision: s.revision, listings: rows.slice(0, limit).map(({ listingId, status, sellerPlayerId, inventoryItemId, currencyId, price, createdAt }) => ({ listingId, status, sellerPlayerId, inventoryItemId, currencyId, price, createdAt })) };
    },
    async Mkt_CreateListing(params) {
      currency(params);
      if (!id(params.players_inventory_item_id) || !Number.isSafeInteger(params.price) || params.price < 1 || params.price > 1000000) fail('INVALID_LISTING');
      return request(params, 'create', (s, p) => {
        const item = p.items[params.players_inventory_item_id];
        if (!item || !tradable.includes(item.inventoryItemId)) fail('ITEM_NOT_TRADABLE');
        const listingId = 'l_' + (s.revision + 1);
        s.listings[listingId] = { listingId, status: 'ACTIVE', sellerPlayerId: pid, inventoryItemId: item.inventoryItemId, item, currencyId: 'COIN', price: params.price, createdAt: Date.now() };
        delete p.items[params.players_inventory_item_id];
        return { listingId };
      });
    },
    async Mkt_BuyListing(params) {
      return request(params, 'buy', (s, p) => {
        const l = listing(s, params.listing_id);
        if (!tradable.includes(l.inventoryItemId)) fail('ITEM_NOT_TRADABLE');
        if (l.sellerPlayerId === pid) fail('CANNOT_BUY_OWN');
        if (l.status !== 'ACTIVE') fail('LISTING_NOT_ACTIVE');
        store.credit(p, -l.price);
        p.items[l.item.playersInventoryItemId] = l.item;
        l.status = 'SOLD'; l.buyerPlayerId = pid; l.earningsStatus = 'AVAILABLE';
        return { ok: true, newPlayersInventoryItemId: l.item.playersInventoryItemId };
      });
    },
    async Mkt_CancelListing(params) {
      return request(params, 'cancel', (s, p) => {
        const l = listing(s, params.listing_id);
        if (l.sellerPlayerId !== pid) fail('SELLER_ONLY');
        if (l.status !== 'ACTIVE') fail('LISTING_NOT_ACTIVE');
        p.items[l.item.playersInventoryItemId] = l.item;
        l.status = 'CANCELLED';
        return { ok: true, returnedPlayersInventoryItemId: l.item.playersInventoryItemId };
      });
    },
    async Mkt_ClaimEarnings(params) {
      currency(params);
      return request(params, 'claim', (s, p) => {
        let claimed = 0;
        for (const l of Object.values(s.listings)) if (l.sellerPlayerId === pid && l.status === 'SOLD' && l.earningsStatus === 'AVAILABLE') {
          claimed += l.price; l.earningsStatus = 'CLAIMED';
        }
        store.credit(p, claimed);
        return { ok: true, claimed };
      });
    },
    async Mkt_Gacha(params) {
      const itemId = catalog[Math.floor(Math.random() * catalog.length)];
      return request(params, 'gacha', (s, p) => {
        store.credit(p, -100);
        const instance = 'i_' + (s.revision + 1);
        p.items[instance] = { inventoryItemId: itemId, playersInventoryItemId: instance, instanceData: {} };
        return { ok: true, inventoryItemId: itemId };
      });
    },
    async Mkt_GrantDemo(params) {
      if (!['coin', 'item'].includes(params.kind)) fail('INVALID_DEMO_KIND');
      const itemId = catalog[Math.floor(Math.random() * catalog.length)];
      return request(params, 'demo_' + params.kind, (s, p) => {
        if (s.demoEnabled !== true) fail('DEMO_DISABLED');
        if ((p.demoGrants || 0) >= 100) fail('DEMO_LIMIT');
        p.demoGrants = (p.demoGrants || 0) + 1;
        if (params.kind === 'coin') store.credit(p, 100);
        else {
          const instance = 'i_' + (s.revision + 1);
          p.items[instance] = { inventoryItemId: itemId, playersInventoryItemId: instance, instanceData: {} };
        }
        return { ok: true, inventoryItemId: params.kind === 'item' ? itemId : null };
      });
    }
  };
}
if (typeof module !== 'undefined') module.exports = { createCloudMarket };

module.exports = async (args) => createCloudMarket(createCloudAdapter(args.context), args.context).Mkt_GetActiveListings(args.params || {});
module.exports.params = {
  "limit": {
    "type": "Numeric",
    "required": false
  },
  "sort": {
    "type": "String",
    "required": false
  }
};
